import type { ProductSeed, ReviewSeed } from "./seed-data";

type ExtProduct = ProductSeed & { imageUrlOverride?: string | null };

export const dmartProducts: ExtProduct[] = [
  {
    name: "Surf Excel Quick Wash Detergent Powder",
    slug: "surf-excel-quick-wash-powder",
    description: "Powerful stain removal detergent for everyday laundry.",
    longDescription: "Surf Excel Quick Wash detergent powder removes tough stains while being gentle on fabrics. Use for bucket or machine wash. Keeps whites bright and colours vibrant.",
    priceCents: 9500,
    compareAtCents: 10800,
    categorySlug: "household",
    emoji: "🧺",
    gradient: "from-blue-400 to-indigo-500",
    unit: "2 kg pack",
    origin: "India",
    stock: 185,
    rating: 4.7,
    reviewCount: 1,
    badge: "Bestseller",
    featured: true,
    organic: false,
    tags: ["laundry", "stain-removal", "everyday"],
    imageUrlOverride: "https://images.pexels.com/photos/21582448/pexels-photo-21582448.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Colgate Strong Teeth Toothpaste",
    slug: "colgate-strong-teeth-tube",
    description: "Advanced fluoride toothpaste for cavity protection.",
    longDescription: "Colgate Strong Teeth toothpaste with active fluoride formula. Strengthens enamel, fights cavities and keeps breath fresh all day. Recommended by dentists worldwide.",
    priceCents: 4500,
    categorySlug: "personal-care",
    emoji: "🪥",
    gradient: "from-red-400 to-blue-500",
    unit: "150 g",
    origin: "India",
    stock: 250,
    rating: 4.8,
    reviewCount: 1,
    badge: "Dentist Choice",
    featured: true,
    organic: false,
    tags: ["oral-care", "dental", "fresh-breath"],
    imageUrlOverride: "https://images.pexels.com/photos/18066458/pexels-photo-18066458.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Horlicks Chocolate Health Drink",
    slug: "horlicks-health-drink",
    description: "Malt-based health drink for strength and energy.",
    longDescription: "Horlicks classic chocolate malt health drink. Rich in vitamins A, C, D and calcium for growing children and active adults. Mix with hot or cold milk for a nutritious beverage.",
    priceCents: 18500,
    compareAtCents: 21500,
    categorySlug: "tea-coffee",
    emoji: "☕",
    gradient: "from-yellow-400 to-green-500",
    unit: "500 g jar",
    origin: "India",
    stock: 110,
    rating: 4.6,
    reviewCount: 1,
    badge: "Super Saver",
    featured: true,
    organic: false,
    tags: ["health-drink", "kids", "nutrition"],
    imageUrlOverride: "https://images.pexels.com/photos/33212331/pexels-photo-33212331.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Lux Rose Silk Soap Bar",
    slug: "lux-soap-bar",
    description: "Silky moisturising soap with rose essence.",
    longDescription: "Lux Rose Silk soap bar with natural rose extracts and moisturising cream. Leaves skin soft, smooth and delicately fragranced. Premium beauty bar for daily bathing.",
    priceCents: 2800,
    categorySlug: "personal-care",
    emoji: "🧼",
    gradient: "from-pink-300 to-rose-400",
    unit: "125 g bar",
    origin: "India",
    stock: 300,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["soap", "beauty", "moisturising"],
    imageUrlOverride: "https://images.pexels.com/photos/16329382/pexels-photo-16329382.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },

  {
    name: "Tata Salt Iodized",
    slug: "tata-salt-iodized",
    description: "Pure iodised salt for daily cooking.",
    longDescription: "Tata Salt is India's most trusted iodised table salt. Fine grain crystals suitable for all cooking, pickling and table use. Essential for thyroid health.",
    priceCents: 1800,
    categorySlug: "atta-rice-grains",
    emoji: "🧂",
    gradient: "from-slate-100 to-blue-200",
    unit: "1 kg pack",
    origin: "India",
    stock: 350,
    rating: 4.7,
    reviewCount: 1,
    badge: "Everyday",
    featured: false,
    organic: false,
    tags: ["salt", "iodised", "everyday"],
    imageUrlOverride: "https://images.pexels.com/photos/21582446/pexels-photo-21582446.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Kissan Mixed Fruit Jam",
    slug: "kissan-mixed-fruit-jam",
    description: "Delicious mixed fruit jam for breakfast.",
    longDescription: "Kissan Mixed Fruit Jam made from real fruit pulp. Perfect spread on bread, toast, parathas and chapatis. No artificial colours or preservatives.",
    priceCents: 6800,
    categorySlug: "bakery-breakfast",
    emoji: "🍓",
    gradient: "from-red-300 to-pink-400",
    unit: "500 g jar",
    origin: "India",
    stock: 120,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["jam", "breakfast", "fruit"],
    imageUrlOverride: "https://images.pexels.com/photos/822647/pexels-photo-822647.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Britannia Milk Bikis Biscuits",
    slug: "britannia-milk-bikis",
    description: "Classic milk biscuits for kids and adults.",
    longDescription: "Britannia Milk Bikis biscuits baked with real milk ingredients. Light, crunchy and mildly sweet. Perfect tiffin snack for children and evening tea companion.",
    priceCents: 3200,
    categorySlug: "biscuits-snacks",
    emoji: "🥛",
    gradient: "from-blue-100 to-yellow-200",
    unit: "200 g pack",
    origin: "India",
    stock: 210,
    rating: 4.6,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["biscuit", "milk", "kids"],
    imageUrlOverride: "https://images.pexels.com/photos/38377147/pexels-photo-38377147.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Dettol Antiseptic Liquid",
    slug: "dettol-antiseptic-liquid",
    description: "Proven germ protection antiseptic liquid.",
    longDescription: "Dettol Antiseptic Liquid kills 99.9% germs on skin, surfaces and laundry. First aid essential for minor cuts, scrapes and household disinfection. Trusted by Indian families for generations.",
    priceCents: 11500,
    categorySlug: "household",
    emoji: "🧴",
    gradient: "from-yellow-400 to-green-500",
    unit: "500 ml bottle",
    origin: "India",
    stock: 160,
    rating: 4.9,
    reviewCount: 1,
    badge: "Trusted",
    featured: true,
    organic: false,
    tags: ["antiseptic", "first-aid", "disinfectant"],
    imageUrlOverride: "https://images.pexels.com/photos/9230357/pexels-photo-9230357.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Kellogg's Corn Flakes Original",
    slug: "kelloggs-original-cereal",
    description: "Crispy corn flakes for a healthy breakfast.",
    longDescription: "Kellogg's Original Corn Flakes made from toasted corn. Low fat, enriched with iron and vitamins. Serve with cold milk and fresh fruits for a quick nutritious breakfast.",
    priceCents: 14900,
    categorySlug: "bakery-breakfast",
    emoji: "🥣",
    gradient: "from-yellow-200 to-orange-300",
    unit: "500 g pack",
    origin: "India",
    stock: 95,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["cereal", "breakfast", "healthy"],
    imageUrlOverride: "https://images.pexels.com/photos/8108216/pexels-photo-8108216.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Dark Fantasy Choco Fills",
    slug: "dark-fantasy-choco-fills",
    description: "Rich chocolate cream sandwich biscuits.",
    longDescription: "Dark Fantasy Choco Fills — decadent chocolate cream between two crunchy, dark cocoa biscuits. Perfect indulgent snack for chocolate lovers. Premium treat with your evening tea.",
    priceCents: 5500,
    categorySlug: "biscuits-snacks",
    emoji: "🍪",
    gradient: "from-amber-800 to-orange-500",
    unit: "150 g pack",
    origin: "India",
    stock: 170,
    rating: 4.7,
    reviewCount: 1,
    badge: "Premium",
    featured: true,
    organic: false,
    tags: ["chocolate", "biscuit", "premium"],
    imageUrlOverride: "https://images.pexels.com/photos/34979322/pexels-photo-34979322.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Patak's Ginger Garlic Paste",
    slug: "ginger-garlic-paste",
    description: "Pure ginger garlic paste for quick cooking.",
    longDescription: "Ready-made ginger garlic paste from select ginger and garlic bulbs. Saves prep time in the kitchen. Essential base for curries, sabzis and gravies.",
    priceCents: 3500,
    categorySlug: "spices-masalas",
    emoji: "🧄",
    gradient: "from-yellow-100 to-green-200",
    unit: "200 g jar",
    origin: "India",
    stock: 180,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["paste", "curry-base", "convenient"],
    imageUrlOverride: "https://images.pexels.com/photos/8108004/pexels-photo-8108004.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Everyday Green Peas",
    slug: "everyday-green-peas",
    description: "Frozen green peas for quick sabzi and pulao.",
    longDescription: "Flash-frozen green peas harvested at peak sweetness. Ready to cook without washing or shelling. Perfect for matar paneer, pulao, sabzi and soups.",
    priceCents: 4900,
    categorySlug: "dairy-eggs",
    emoji: "🟢",
    gradient: "from-green-300 to-emerald-400",
    unit: "500 g pack",
    origin: "India",
    stock: 140,
    rating: 4.4,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["frozen", "peas", "convenient"],
    imageUrlOverride: "https://images.pexels.com/photos/4224259/pexels-photo-4224259.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Saffola Active Cooking Oil",
    slug: "saffola-active-oil",
    description: "Heart-healthy refined cooking oil.",
    longDescription: "Saffola Active with Losorb technology reduces oil absorption. A blend of sunflower and rice bran oils rich in vitamin E. Ideal for everyday deep frying and sautéing.",
    priceCents: 19500,
    categorySlug: "oils-ghee",
    emoji: "🌻",
    gradient: "from-yellow-200 to-amber-400",
    unit: "1 L bottle",
    origin: "India",
    stock: 105,
    rating: 4.6,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["heart-healthy", "cooking-oil", "everyday"],
    imageUrlOverride: "https://images.pexels.com/photos/34270746/pexels-photo-34270746.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "MTR Rava Idli Mix",
    slug: "mtr-rava-idli-mix",
    description: "Instant rava idli mix for fluffy idlis in minutes.",
    longDescription: "MTR Rava Idli Mix — just add water and steam! Ready in 10 minutes. Makes soft, fluffy idlis and crispy dosas. Authentic Karnataka style taste.",
    priceCents: 4200,
    categorySlug: "atta-rice-grains",
    emoji: "⚪",
    gradient: "from-white to-stone-200",
    unit: "500 g pack",
    origin: "Bengaluru",
    stock: 130,
    rating: 4.6,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["idli", "instant-mix", "south-indian"],
    imageUrlOverride: "https://images.pexels.com/photos/8108057/pexels-photo-8108057.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Lijjat Papad Large",
    slug: "lijjat-papad",
    description: "Crispy papad for everyday meals.",
    longDescription: "Lijjat Papad — thin, crunchy papads ready to roast or fry. Made from urad dal flour. Essential Indian accompaniment for every thali meal.",
    priceCents: 3200,
    categorySlug: "biscuits-snacks",
    emoji: "🫓",
    gradient: "from-amber-100 to-orange-200",
    unit: "200 g pack",
    origin: "India",
    stock: 190,
    rating: 4.7,
    reviewCount: 1,
    badge: "Household Name",
    featured: false,
    organic: false,
    tags: ["papad", "snack", "thali"],
    imageUrlOverride: "https://images.pexels.com/photos/4224250/pexels-photo-4224250.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Tata Tea Premium Leaf",
    slug: "tata-tea-premium",
    description: "Rich and strong leaf tea for perfect cups.",
    longDescription: "Tata Tea Premium — carefully selected tea leaves for rich colour and full-bodied taste. Brew a strong, refreshing cup that energises your morning.",
    priceCents: 13000,
    compareAtCents: 15000,
    categorySlug: "tea-coffee",
    emoji: "🍵",
    gradient: "from-amber-600 to-orange-700",
    unit: "500 g pack",
    origin: "Assam & Darjeeling",
    stock: 155,
    rating: 4.7,
    reviewCount: 1,
    badge: "Premium Leaf",
    featured: true,
    organic: false,
    tags: ["black-tea", "leaf-tea", "energy"],
    imageUrlOverride: "https://images.pexels.com/photos/35285855/pexels-photo-35285855.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "YIPEE Noodles Masala",
    slug: "yipee-noodles-masala",
    description: "Quick masala noodles snack in 2 minutes.",
    longDescription: "YIPEE Masala Noodles with flavourful spice mix. Just add water and microwave for 2 minutes. Perfect quick snack for kids and adults. A fun meal anytime.",
    priceCents: 1200,
    categorySlug: "biscuits-snacks",
    emoji: "🍜",
    gradient: "from-orange-300 to-red-400",
    unit: "70 g pack",
    origin: "India",
    stock: 280,
    rating: 4.4,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["noodles", "instant", "kids"],
    imageUrlOverride: "https://images.pexels.com/photos/18698263/pexels-photo-18698263.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Dabur Amla Hair Oil",
    slug: "dabur-amla-hair-oil",
    description: "Natural amla hair oil for strong and shiny hair.",
    longDescription: "Dabur Amla Hair Oil enriched with pure amla extracts. Promotes hair growth, reduces hair fall and adds natural black shine. Traditional Indian hair care remedy.",
    priceCents: 8900,
    categorySlug: "personal-care",
    emoji: "💆",
    gradient: "from-green-500 to-amber-400",
    unit: "200 ml bottle",
    origin: "India",
    stock: 135,
    rating: 4.7,
    reviewCount: 1,
    featured: true,
    organic: false,
    tags: ["hair-oil", "amla", "traditional"],
    imageUrlOverride: "https://images.pexels.com/photos/18066458/pexels-photo-18066458.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Madhur Pure Sugar",
    slug: "madhur-sugar",
    description: "Fine grain pure cane sugar for daily use.",
    longDescription: "Madhur Pure Crystal Sugar — finest quality refined cane sugar. Used for chai, sweets, and all cooking. Clean, white, and perfectly sweet.",
    priceCents: 4900,
    categorySlug: "atta-rice-grains",
    emoji: "⬜",
    gradient: "from-white to-stone-100",
    unit: "1 kg pack",
    origin: "India",
    stock: 230,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["sugar", "everyday", "cooking"],
    imageUrlOverride: "https://images.pexels.com/photos/21582446/pexels-photo-21582446.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Fortune Refined Sunflower Oil",
    slug: "fortune-bottle-sunflower-oil",
    description: "Light sunflower oil for everyday cooking.",
    longDescription: "Fortune Sunflower Oil — light and cholesterol-free. Suitable for daily cooking, frying and sautéing. Rich source of natural Vitamin E.",
    priceCents: 17900,
    categorySlug: "oils-ghee",
    emoji: "🌻",
    gradient: "from-amber-100 to-yellow-300",
    unit: "1 L bottle",
    origin: "India",
    stock: 145,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["sunflower", "light", "healthy"],
    imageUrlOverride: "https://images.pexels.com/photos/34270746/pexels-photo-34270746.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Haldiram's All In One Namkeen",
    slug: "haldiram-all-in-one",
    description: "Mixed spicy namkeen with everything.",
    longDescription: "Haldiram's All In One Namkeen — crunchy blend of peanuts, sev, lentils and cornflakes. Seasoned with tangy spices. Perfect evening snack with hot chai.",
    priceCents: 9900,
    categorySlug: "biscuits-snacks",
    emoji: "🥨",
    gradient: "from-red-200 to-amber-400",
    unit: "400 g pack",
    origin: "India",
    stock: 165,
    rating: 4.8,
    reviewCount: 1,
    badge: "Premium Mix",
    featured: true,
    organic: false,
    tags: ["namkeen", "spicy", "party"],
    imageUrlOverride: "https://images.pexels.com/photos/21582447/pexels-photo-21582447.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "LiveWell Chicken Sausages",
    slug: "livewell-chicken-sausages",
    description: "Ready-to-fry chicken sausages for breakfast.",
    longDescription: "LiveWell premium chicken sausages made from selected chicken cuts. Perfect for breakfast, party platters and rolls. Ready in 3 minutes on a hot pan.",
    priceCents: 9900,
    categorySlug: "dairy-eggs",
    emoji: "🌭",
    gradient: "from-red-300 to-amber-300",
    unit: "250 g pack",
    origin: "India",
    stock: 85,
    rating: 4.4,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["frozen", "chicken", "breakfast"],
    imageUrlOverride: "https://images.pexels.com/photos/18698239/pexels-photo-18698239.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Parle 20-20 Magic Masala",
    slug: "parle-20-20-masala",
    description: "Crunchy masala flavoured biscuits.",
    longDescription: "Parle 20-20 Magic Masala — crunchy, salted biscuits with tangy masala seasoning. A unique snacking experience with your evening tea or as a quick snack.",
    priceCents: 2500,
    categorySlug: "biscuits-snacks",
    emoji: "🔶",
    gradient: "from-orange-300 to-red-400",
    unit: "150 g pack",
    origin: "India",
    stock: 220,
    rating: 4.3,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["salty-biscuit", "masala", "snack"],
    imageUrlOverride: "https://images.pexels.com/photos/38377147/pexels-photo-38377147.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Nestle Milkmaid Sweet Condensed Milk",
    slug: "milkmaid-sweetened",
    description: "Thick sweetened condensed milk for desserts.",
    longDescription: "Nestle Milkmaid is pure sweetened condensed milk made from fresh cow milk. Ready to use for instant desserts like kheer, halwa, ice cream and milkshakes.",
    priceCents: 10500,
    categorySlug: "dairy-eggs",
    emoji: "🥛",
    gradient: "from-yellow-100 to-blue-200",
    unit: "400 g tin",
    origin: "India",
    stock: 90,
    rating: 4.7,
    reviewCount: 1,
    badge: "Dessert Special",
    featured: true,
    organic: false,
    tags: ["milkmaid", "dessert", "sweetened"],
    imageUrlOverride: "https://images.pexels.com/photos/36183642/pexels-photo-36183642.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },

  {
    name: "Fortune Chakki Fresh Atta",
    slug: "fortune-chakki-atta",
    description: "Stone-ground whole wheat atta for soft rotis.",
    longDescription: "Fortune Chakki Fresh Atta is stone-ground from select wheat grains. Fresh, soft and nutritious rotis every time. Rich in natural fibre and essential minerals.",
    priceCents: 15500,
    categorySlug: "atta-rice-grains",
    emoji: "🌾",
    gradient: "from-amber-100 to-yellow-300",
    unit: "5 kg pack",
    origin: "India",
    stock: 145,
    rating: 4.6,
    reviewCount: 1,
    badge: "Family Pack",
    featured: true,
    organic: false,
    tags: ["atta", "wheat", "essential"],
    imageUrlOverride: undefined,
  },
  {
    name: "Amul Masti Spiced Buttermilk",
    slug: "amul-masti-buttermilk",
    description: "Refreshing spiced buttermilk, ready to drink.",
    longDescription: "Amul Masti Spiced Buttermilk — traditional chaas ready to enjoy. Made from fresh curd with a touch of salt, cumin and mint. Perfect digestive after meals.",
    priceCents: 2500,
    categorySlug: "tea-coffee",
    emoji: "🥛",
    gradient: "from-white to-yellow-100",
    unit: "200 ml pack",
    origin: "Gujarat",
    stock: 200,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["buttermilk", "chaas", "digestive"],
    imageUrlOverride: "https://images.pexels.com/photos/37515883/pexels-photo-37515883.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Tiger Biscuits",
    slug: "tiger-biscuits",
    description: "Crunchy glucose biscuits with protein power.",
    longDescription: "Tiger Biscuits — crunchy glucose biscuits fortified with protein. Perfect for growing children and active lifestyles. A guaranteed smile with every bite.",
    priceCents: 1500,
    categorySlug: "biscuits-snacks",
    emoji: "🐯",
    gradient: "from-orange-400 to-yellow-400",
    unit: "200 g pack",
    origin: "India",
    stock: 260,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["biscuit", "glucose", "kids"],
    imageUrlOverride: "https://images.pexels.com/photos/34979322/pexels-photo-34979322.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Himalaya Gentle Baby Soap",
    slug: "himalaya-baby-soap",
    description: "Gentle baby soap with natural extracts.",
    longDescription: "Himalaya Gentle Baby Soap with olive oil and milk extracts. Clinically tested for baby's delicate skin. Soap-free, mild cleansing for gentle bathing.",
    priceCents: 4900,
    categorySlug: "personal-care",
    emoji: "👶",
    gradient: "from-blue-100 to-white",
    unit: "75 g bar",
    origin: "India",
    stock: 175,
    rating: 4.6,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["baby", "soap", "gentle"],
    imageUrlOverride: "https://images.pexels.com/photos/16329382/pexels-photo-16329382.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Cadbury Perk Chocolate",
    slug: "cadbury-perk",
    description: "Wafers and chocolate layered snack bar.",
    longDescription: "Cadbury Perk — crispy wafers layered with smooth Cadbury milk chocolate. Light, crunchy and absolutely irresistible. Perfect anytime snack bar.",
    priceCents: 1500,
    categorySlug: "biscuits-snacks",
    emoji: "🍫",
    gradient: "from-purple-700 to-amber-600",
    unit: "32 g bar",
    origin: "India",
    stock: 300,
    rating: 4.7,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["chocolate", "wafers", "snack"],
    imageUrlOverride: undefined,
  },
  {
    name: "Rin Advanced Detergent Bar",
    slug: "rin-detergent-bar",
    description: "Stain removing laundry bar for hand wash.",
    longDescription: "Rin Advanced Detergent Bar with advanced stain removal formula. Effectively removes tough stains from clothes without damaging fabric. Ideal for daily hand wash laundry.",
    priceCents: 3800,
    categorySlug: "household",
    emoji: "🧼",
    gradient: "from-blue-400 to-cyan-300",
    unit: "250 g bar",
    origin: "India",
    stock: 195,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["detergent", "laundry", "stain-removal"],
    imageUrlOverride: "https://images.pexels.com/photos/9230462/pexels-photo-9230462.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Nourish Shine Conditioner",
    slug: "nourish-conditioner",
    description: "Smooth and shine hair conditioner.",
    longDescription: "Nourish Shine Conditioner with argan oil and vitamin E. Detangles hair and adds incredible shine. For soft, manageable and silky smooth hair.",
    priceCents: 5500,
    categorySlug: "personal-care",
    emoji: "💇",
    gradient: "from-pink-300 to-amber-400",
    unit: "180 ml bottle",
    origin: "India",
    stock: 100,
    rating: 4.4,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["conditioner", "hair-care", "shine"],
    imageUrlOverride: "https://images.pexels.com/photos/18066458/pexels-photo-18066458.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Maggi Hot & Sweet Sauce",
    slug: "maggi-hot-sweet-sauce",
    description: "Perfect dipping sauce combo for every meal.",
    longDescription: "Maggi Hot & Sweet Sauce — the perfect balance of spicy and sweet. Ideal as a dip for snacks, chaat, momos and sandwiches. Tangy and delicious.",
    priceCents: 4500,
    categorySlug: "spices-masalas",
    emoji: "🍅",
    gradient: "from-red-400 to-orange-500",
    unit: "500 g bottle",
    origin: "India",
    stock: 145,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["sauce", "dip", "snacks"],
    imageUrlOverride: "https://images.pexels.com/photos/8108004/pexels-photo-8108004.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Britannia Cheese Slices",
    slug: "britannia-cheese-slices-supreme",
    description: "Creamy processed cheese slices for sandwiches.",
    longDescription: "Britannia Cheese Slices made from real cheddar cheese. Perfect for sandwiches, burgers, toast and wraps. Individually wrapped for freshness. Kids' lunchbox favourite.",
    priceCents: 12500,
    compareAtCents: 14900,
    categorySlug: "dairy-eggs",
    emoji: "🧀",
    gradient: "from-yellow-200 to-orange-300",
    unit: "200 g (10 slices)",
    origin: "India",
    stock: 95,
    rating: 4.6,
    reviewCount: 1,
    badge: "Lunchbox",
    featured: true,
    organic: false,
    tags: ["cheese", "sandwich", "kids"],
    imageUrlOverride: undefined,
  },
  {
    name: "Everest Pav Bhaji Masala",
    slug: "everest-pav-bhaji-masala",
    description: "Restaurant-style pav bhaji masala blend.",
    longDescription: "Everest Pav Bhaji Masala — authentic Mumbai street food spice blend. Made with select spices for the perfect bhaji taste. Just add to bhaji for restaurant style flavour.",
    priceCents: 2200,
    categorySlug: "spices-masalas",
    emoji: "🥘",
    gradient: "from-orange-300 to-red-500",
    unit: "100 g pack",
    origin: "India",
    stock: 185,
    rating: 4.8,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["masala", "pav-bhaji", "mumbai"],
    imageUrlOverride: undefined,
  },
  {
    name: "Garnier Fructis Shampoo",
    slug: "garnier-fructis-shampoo",
    description: "Longer, stronger hair with fruit actives.",
    longDescription: "Garnier Fructis Shampoo with active fruit concentrate and vitamin E. Strengthens hair from root to tip. Leaves hair shiny, smooth and manageable.",
    priceCents: 8500,
    categorySlug: "personal-care",
    emoji: "🍊",
    gradient: "from-green-300 to-amber-400",
    unit: "340 ml bottle",
    origin: "India",
    stock: 125,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["shampoo", "hair-care", "fructis"],
    imageUrlOverride: "https://images.pexels.com/photos/18066458/pexels-photo-18066458.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Coca-Cola Zero Sugar Can",
    slug: "coca-cola-zero-can",
    description: "Zero sugar cola with the same great taste.",
    longDescription: "Coca-Cola Zero Sugar has all the great Coca-Cola taste with zero sugar and zero calories. Perfect when you want the real thing without the sugar.",
    priceCents: 4000,
    categorySlug: "tea-coffee",
    emoji: "🥫",
    gradient: "from-red-700 to-red-500",
    unit: "300 ml can (pack of 6)",
    origin: "India",
    stock: 200,
    rating: 4.6,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["cola", "zero-sugar", "party"],
    imageUrlOverride: "https://images.pexels.com/photos/11942007/pexels-photo-11942007.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Harpic Power Plus Toilet Cleaner",
    slug: "harpic-plus-cleaner",
    description: "Thick liquid toilet cleaner for tough stains.",
    longDescription: "Harpic Power Plus disinfectant toilet cleaner removes tough limescale, rust and deep stains. Thick liquid clings to the bowl surface. Leaves toilet clean and fresh.",
    priceCents: 12500,
    categorySlug: "household",
    emoji: "🚽",
    gradient: "from-blue-600 to-indigo-700",
    unit: "750 ml bottle",
    origin: "India",
    stock: 130,
    rating: 4.6,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["toilet-cleaner", "disinfectant", "hygiene"],
    imageUrlOverride: undefined,
  },
  {
    name: "Surf Excel Matic Liquid Detergent",
    slug: "surf-excel-matic",
    description: "Front load washing machine liquid detergent.",
    longDescription: "Surf Excel Matic Liquid Detergent specially formulated for front load washing machines. Low suds, powerful stain removal. Leaves clothes fresh and bright with every wash.",
    priceCents: 14800,
    categorySlug: "household",
    emoji: "🧺",
    gradient: "from-blue-500 to-indigo-400",
    unit: "1 L bottle",
    origin: "India",
    stock: 110,
    rating: 4.6,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["liquid-detergent", "machine-wash", "premium"],
    imageUrlOverride: "https://images.pexels.com/photos/9230462/pexels-photo-9230462.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
  {
    name: "Tata I-Shakti Tea Bags",
    slug: "tata-ishakti-tea-bags",
    description: "Convenient tea bags with rich flavour.",
    longDescription: "Tata I-Shakti Tea Bags — premium Assam tea in convenient bag. One bag, one perfect cup. Strong, refreshing tea with rich golden colour. Brew at home or office.",
    priceCents: 8900,
    categorySlug: "tea-coffee",
    emoji: "🫖",
    gradient: "from-amber-500 to-brown-600",
    unit: "100 tea bags",
    origin: "Assam",
    stock: 140,
    rating: 4.6,
    reviewCount: 1,
    badge: "Best Value",
    featured: false,
    organic: false,
    tags: ["tea-bag", "assam", "convenient"],
    imageUrlOverride: "https://images.pexels.com/photos/35285855/pexels-photo-35285855.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  },
];

export const dmartReviewSeed: ReviewSeed[] = [
  { productSlug: "surf-excel-quick-wash-powder", author: "Shweta K.", rating: 5, title: "Excellent stain removal", body: "My kids' uniform kurtas easily clean ho jate hain with this. No more worrying about stubborn stains.", verified: true },
  { productSlug: "colgate-strong-teeth-tube", author: "Dr. Anil M.", rating: 5, title: "Doctor recommended", body: "I recommend Colgate to all my patients. Reliable cavity protection and fresh breath.", verified: true },
  { productSlug: "horlicks-health-drink", author: "Nirmala R.", rating: 4, title: "Kids love it", body: "My children drink milk happily now. Can see improvement in their energy levels.", verified: true },
  { productSlug: "lux-soap-bar", author: "Pooja S.", rating: 5, title: "Soft skin", body: "Lux ka rose fragrance bahut achcha lagta hai. Skin soft and smooth feel hoti hai.", verified: true },
  { productSlug: "lizol-floor-cleaner", author: "Rohan D.", rating: 5, title: "Fresh and clean", body: "Ghar mein lemon fragrance bhar deta hai. Floors clean and shining rehte hain.", verified: true },
  { productSlug: "tata-salt-iodized", author: "Manisha B.", rating: 5, title: "Always reliable", body: "Never switched from Tata Salt. Pure and correct quantity every time.", verified: true },
  { productSlug: "kissan-mixed-fruit-jam", author: "Aarav S.", rating: 4, title: "Yummy on toast", body: "Kids school breakfast mein favourite. Real fruit taste achha lagta hai.", verified: true },
  { productSlug: "britannia-milk-bikis", author: "Geeta P.", rating: 5, title: "Kids love them", body: "Soft, not too sweet. Perfect for small children. Tiffin mein daily rakhti hoon.", verified: true },
  { productSlug: "dettol-antiseptic-liquid", author: "Dr. Raja S.", rating: 5, title: "Home essential", body: "Every home should have Dettol. For cuts, laundry, floors — multipurpose protection.", verified: true },
  { productSlug: "tata-tea-premium", author: "Vinod R.", rating: 5, title: "Strong morning chai", body: "Perfect for cutting chai. Strong, rich colour and full-bodied taste. Best tea.", verified: true },
  { productSlug: "haldiram-all-in-one", author: "Kavita J.", rating: 5, title: "Party mix", body: "Guest aate hain toh yeh nikal deti hoon. Sab log enjoy karte hain. Crunchy and tasty.", verified: true },
  { productSlug: "milkmaid-sweetened", author: "Radhika T.", rating: 5, title: "Easy desserts", body: "Kheer instant ban jaati hai! Best quality, no compromise on taste.", verified: true },
  { productSlug: "fortune-chakki-atta", author: "Rekha M.", rating: 4, title: "Soft rotis", body: "Soft, fluffy rotis every time. Good price for a 5kg pack.", verified: true },
  { productSlug: "britannia-cheese-slices-supreme", author: "Neha A.", rating: 5, title: "Kids lunch essential", body: "Sandwich cubes for school — easy to pack and kids love the taste.", verified: true },
  { productSlug: "everest-pav-bhaji-masala", author: "Sameer W.", rating: 5, title: "Real Mumbai taste", body: "Ghar mein stall jaisa pav bhaji banta hai. Best masala ever.", verified: true },
  { productSlug: "coca-cola-zero-can", author: "Vivek G.", rating: 4, title: "Sugar free cola", body: "Same amazing taste with zero guilt. Diet friendly option.", verified: true },
  { productSlug: "surf-excel-matic", author: "Sneha V.", rating: 5, title: "Perfect for front load", body: "Low suds formula works great in my IFB machine. Clothes fresh and stain free.", verified: true },
  { productSlug: "tata-ishakti-tea-bags", author: "Rakesh P.", rating: 4, title: "Office favourite", body: "100 bags ka packet office mein rakhte hain. Ek cup mein perfect brew.", verified: true },
];
