import type { ProductSeed, ReviewSeed } from "./seed-data";

export const categoryImageBySlug: Record<string, string> = {
  "atta-rice-grains": "https://images.pexels.com/photos/17236198/pexels-photo-17236198.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "dal-pulses": "https://images.pexels.com/photos/8108057/pexels-photo-8108057.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "oils-ghee": "https://images.pexels.com/photos/4224266/pexels-photo-4224266.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "spices-masalas": "https://images.pexels.com/photos/12419503/pexels-photo-12419503.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "sugar-salt": "https://images.pexels.com/photos/21582446/pexels-photo-21582446.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "tea-coffee": "https://images.pexels.com/photos/35285855/pexels-photo-35285855.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "biscuits-snacks": "https://images.pexels.com/photos/21582447/pexels-photo-21582447.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "fresh-produce": "/images/hero-groceries.jpg",
  "dairy-eggs": "/images/products/amul-milk.jpg",
  "bakery-breakfast": "https://images.pexels.com/photos/17236198/pexels-photo-17236198.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "personal-care": "https://images.pexels.com/photos/35285852/pexels-photo-35285852.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  household: "https://images.pexels.com/photos/21582448/pexels-photo-21582448.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
};

export const productImageOverrides: Record<string, string> = {
  "fortune-sunflower-oil": "/images/products/fortune-oil.jpg",
  "amul-cow-ghee": "/images/products/amul-ghee.jpg",
  "tata-tea-gold": "/images/products/tata-tea-gold.jpg",
  "parle-gluco-biscuits": "/images/products/parle-g.jpg",
  "haldiram-aloo-bhujia": "/images/products/haldiram-bhujia.jpg",
  "ashirwad-whole-wheat-atta": "/images/products/ashirwad-atta.jpg",
  "india-gate-basmati-rice": "/images/products/india-gate-rice.jpg",
  "everest-kitchen-king": "/images/products/everest-masala.jpg",
  "amul-taaza-milk": "/images/products/amul-milk.jpg",
};

export const extraProductSeed: ProductSeed[] = [
  {
    name: "24 Mantra Organic Wheat Atta",
    slug: "24-mantra-organic-atta",
    description: "Certified organic atta for soft, wholesome rotis.",
    longDescription:
      "Stone-ground organic whole wheat atta from certified farms. Naturally rich in fibre and perfect for soft phulkas, parathas and thepla.",
    priceCents: 42900,
    compareAtCents: 45900,
    categorySlug: "atta-rice-grains",
    emoji: "🌾",
    gradient: "from-emerald-200 to-amber-200",
    unit: "5 kg pack",
    origin: "India",
    stock: 48,
    rating: 4.7,
    reviewCount: 1,
    badge: "Organic",
    featured: true,
    organic: true,
    tags: ["organic", "atta", "healthy"],
  },
  {
    name: "Daawat Rozana Basmati Rice",
    slug: "daawat-rozana-basmati",
    description: "Budget-friendly basmati for daily pulao and jeera rice.",
    longDescription:
      "A dependable everyday basmati with good elongation and aroma. Great for office tiffin pulao, jeera rice and light biryani.",
    priceCents: 48900,
    categorySlug: "atta-rice-grains",
    emoji: "🍚",
    gradient: "from-slate-100 to-green-200",
    unit: "5 kg bag",
    origin: "Punjab",
    stock: 72,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["rice", "basmati", "daily"],
  },
  {
    name: "Brown Rice",
    slug: "brown-rice",
    description: "Nutty wholegrain rice for healthier meals.",
    longDescription:
      "Unpolished brown rice with bran intact for extra fibre. Ideal for health-focused lunches, grain bowls and simple dal-rice.",
    priceCents: 15900,
    categorySlug: "atta-rice-grains",
    emoji: "🍚",
    gradient: "from-stone-300 to-amber-300",
    unit: "1 kg pack",
    origin: "India",
    stock: 68,
    rating: 4.4,
    reviewCount: 1,
    featured: false,
    organic: true,
    tags: ["wholegrain", "healthy", "fibre"],
  },
  {
    name: "Besan Gram Flour",
    slug: "besan-gram-flour",
    description: "Fine chana besan for pakoda, dhokla and kadhi.",
    longDescription:
      "Finely milled gram flour from premium chana dal. Makes crispy pakodas, fluffy dhokla, kadhi and ladoos with consistent texture.",
    priceCents: 9900,
    categorySlug: "atta-rice-grains",
    emoji: "🟨",
    gradient: "from-yellow-200 to-orange-300",
    unit: "1 kg pack",
    origin: "India",
    stock: 115,
    rating: 4.6,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["besan", "snacks", "kadhi"],
  },
  {
    name: "Urad Dal White",
    slug: "urad-dal-white",
    description: "Split urad dal for idli, dosa and dal makhani.",
    longDescription:
      "Clean white urad dal that grinds smooth for idli-dosa batter and cooks creamy for North Indian dal makhani.",
    priceCents: 16900,
    categorySlug: "dal-pulses",
    emoji: "⚪",
    gradient: "from-white to-stone-200",
    unit: "1 kg pack",
    origin: "Madhya Pradesh",
    stock: 78,
    rating: 4.6,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["idli", "dosa", "protein"],
  },
  {
    name: "Green Moong Whole",
    slug: "green-moong-whole",
    description: "Whole green gram for sprouts and usal.",
    longDescription:
      "Premium whole green moong with excellent sprouting quality. Use for healthy salads, usal, dal and protein-rich snacks.",
    priceCents: 13900,
    categorySlug: "dal-pulses",
    emoji: "🟢",
    gradient: "from-lime-200 to-green-400",
    unit: "1 kg pack",
    origin: "Rajasthan",
    stock: 98,
    rating: 4.7,
    reviewCount: 1,
    featured: true,
    organic: false,
    tags: ["sprouts", "protein", "healthy"],
  },
  {
    name: "Black Chana",
    slug: "black-chana",
    description: "Kala chana for sundal, usal and chana curry.",
    longDescription:
      "Hearty black chickpeas, rich in protein and fibre. Soak overnight for classic kala chana curry, sundal or Maharashtrian usal.",
    priceCents: 11900,
    categorySlug: "dal-pulses",
    emoji: "⚫",
    gradient: "from-stone-700 to-amber-500",
    unit: "1 kg pack",
    origin: "India",
    stock: 88,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["chana", "protein", "fibre"],
  },
  {
    name: "Organic Groundnut Oil",
    slug: "organic-groundnut-oil",
    description: "Cold-pressed shengdana tel for authentic cooking.",
    longDescription:
      "Wood-pressed groundnut oil with a rich nutty aroma. Excellent for Maharashtrian and Gujarati cooking, tadka, poha, thepla and frying.",
    priceCents: 34900,
    compareAtCents: 37900,
    categorySlug: "oils-ghee",
    emoji: "🥜",
    gradient: "from-orange-200 to-amber-500",
    unit: "1 litre bottle",
    origin: "Gujarat",
    stock: 64,
    rating: 4.8,
    reviewCount: 2,
    badge: "Cold Pressed",
    featured: true,
    organic: true,
    tags: ["groundnut", "cold-pressed", "premium"],
  },
  {
    name: "Parachute Coconut Oil",
    slug: "parachute-coconut-oil",
    description: "Pure coconut oil for hair and cooking use.",
    longDescription:
      "Trusted pure coconut oil with natural coconut aroma. Use for hair nourishment, oil massage and traditional cooking.",
    priceCents: 10900,
    categorySlug: "oils-ghee",
    emoji: "🥥",
    gradient: "from-cyan-100 to-blue-300",
    unit: "200 ml bottle",
    origin: "India",
    stock: 120,
    rating: 4.7,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["coconut", "hair-care", "multipurpose"],
  },
  {
    name: "Til Oil Sesame",
    slug: "sesame-til-oil",
    description: "Aromatic til tel for pickles and traditional dishes.",
    longDescription:
      "Nutty sesame oil used in South Indian tempering, pickles and winter recipes. Rich flavour with authentic aroma.",
    priceCents: 22900,
    categorySlug: "oils-ghee",
    emoji: "🫙",
    gradient: "from-stone-200 to-amber-500",
    unit: "500 ml bottle",
    origin: "Tamil Nadu",
    stock: 62,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["sesame", "pickle", "traditional"],
  },
  {
    name: "Coriander Powder",
    slug: "coriander-powder",
    description: "Fresh dhania powder for everyday sabzi.",
    longDescription:
      "Aromatic coriander powder ground from clean, sun-dried coriander seeds. Gives body and gentle citrus warmth to curries.",
    priceCents: 8900,
    categorySlug: "spices-masalas",
    emoji: "🌿",
    gradient: "from-lime-200 to-emerald-300",
    unit: "200 g pack",
    origin: "Rajasthan",
    stock: 150,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["dhania", "masala", "daily"],
  },
  {
    name: "Black Pepper Whole",
    slug: "black-pepper-whole",
    description: "Bold whole kali mirch for fresh grinding.",
    longDescription:
      "Premium whole black peppercorns with sharp aroma. Crush fresh over soup, eggs, rasam or masala chai.",
    priceCents: 19900,
    categorySlug: "spices-masalas",
    emoji: "⚫",
    gradient: "from-stone-900 to-stone-500",
    unit: "100 g jar",
    origin: "Kerala",
    stock: 90,
    rating: 4.7,
    reviewCount: 1,
    badge: "Premium",
    featured: false,
    organic: false,
    tags: ["pepper", "whole-spice", "kerala"],
  },
  {
    name: "Pav Bhaji Masala",
    slug: "pav-bhaji-masala",
    description: "Mumbai-style masala for buttery pav bhaji.",
    longDescription:
      "A robust masala blend that gives bhaji the perfect Mumbai street-food taste. Add butter, onions and pav — sorted.",
    priceCents: 6900,
    categorySlug: "spices-masalas",
    emoji: "🍛",
    gradient: "from-orange-300 to-red-500",
    unit: "100 g pack",
    origin: "India",
    stock: 130,
    rating: 4.8,
    reviewCount: 1,
    featured: true,
    organic: false,
    tags: ["mumbai", "street-food", "masala"],
  },
  {
    name: "Brown Sugar",
    slug: "brown-sugar",
    description: "Soft brown sugar for tea, baking and desserts.",
    longDescription:
      "Moist brown sugar with rich molasses flavour. Perfect for cakes, cookies, coffee, kheer and caramel-style desserts.",
    priceCents: 8900,
    categorySlug: "sugar-salt",
    emoji: "🟤",
    gradient: "from-amber-700 to-stone-500",
    unit: "500 g pack",
    origin: "India",
    stock: 85,
    rating: 4.4,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["baking", "sugar", "dessert"],
  },
  {
    name: "Himalayan Pink Salt",
    slug: "himalayan-pink-salt",
    description: "Mineral-rich pink salt crystals.",
    longDescription:
      "Natural pink salt crystals with gentle mineral taste. Use in cooking, salads, chaas or finishing salts.",
    priceCents: 7900,
    categorySlug: "sugar-salt",
    emoji: "🧂",
    gradient: "from-pink-200 to-rose-300",
    unit: "500 g jar",
    origin: "Himalayan region",
    stock: 76,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: true,
    tags: ["pink-salt", "natural", "mineral"],
  },
  {
    name: "Green Tea Bags",
    slug: "green-tea-bags",
    description: "Light detox green tea for daily wellness.",
    longDescription:
      "Refreshing green tea bags with delicate taste and antioxidants. Brew for 2 minutes for a clean, energising cup.",
    priceCents: 14900,
    categorySlug: "tea-coffee",
    emoji: "🍵",
    gradient: "from-green-200 to-emerald-400",
    unit: "25 tea bags",
    origin: "Assam",
    stock: 95,
    rating: 4.4,
    reviewCount: 1,
    badge: "Wellness",
    featured: false,
    organic: false,
    tags: ["green-tea", "wellness", "antioxidant"],
  },
  {
    name: "Bournvita Health Drink",
    slug: "bournvita-health-drink",
    description: "Chocolate malt drink for kids and adults.",
    longDescription:
      "Cadbury Bournvita chocolate malt drink. Mix with hot or cold milk for a tasty energy boost with vitamins and minerals.",
    priceCents: 22900,
    categorySlug: "tea-coffee",
    emoji: "🍫",
    gradient: "from-purple-600 to-amber-700",
    unit: "500 g jar",
    origin: "India",
    stock: 80,
    rating: 4.6,
    reviewCount: 1,
    featured: true,
    organic: false,
    tags: ["health-drink", "kids", "chocolate"],
  },
  {
    name: "Thums Up Soft Drink",
    slug: "thums-up-soft-drink",
    description: "Strong fizzy cola, perfect with spicy meals.",
    longDescription:
      "India's bold cola with extra fizz and punch. Best served chilled with pav bhaji, biryani, samosa or weekend meals.",
    priceCents: 9500,
    categorySlug: "tea-coffee",
    emoji: "🥤",
    gradient: "from-red-900 to-blue-900",
    unit: "2 litre bottle",
    origin: "India",
    stock: 105,
    rating: 4.6,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["cola", "party", "cold-drink"],
  },
  {
    name: "Maggi 2-Minute Noodles",
    slug: "maggi-2-minute-noodles",
    description: "Masala noodles for quick hunger fixes.",
    longDescription:
      "The iconic Maggi masala noodles. Ready in minutes, endlessly customisable with onion, tomato, egg or cheese.",
    priceCents: 1400,
    categorySlug: "biscuits-snacks",
    emoji: "🍜",
    gradient: "from-yellow-300 to-red-400",
    unit: "70 g pack",
    origin: "India",
    stock: 300,
    rating: 4.9,
    reviewCount: 2,
    badge: "Iconic",
    featured: true,
    organic: false,
    tags: ["noodles", "quick", "classic"],
  },
  {
    name: "Bingo Mad Angles Achari Masti",
    slug: "bingo-mad-angles-achari",
    description: "Triangular crispy chips with achari masala.",
    longDescription:
      "Crunchy triangle chips with tangy achari seasoning. A bold snack for movie nights and evening chai.",
    priceCents: 2000,
    categorySlug: "biscuits-snacks",
    emoji: "🔺",
    gradient: "from-orange-500 to-red-500",
    unit: "66 g pack",
    origin: "India",
    stock: 240,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["chips", "achari", "snacks"],
  },
  {
    name: "Marie Gold Biscuits",
    slug: "marie-gold-biscuits",
    description: "Light tea biscuits for everyday dipping.",
    longDescription:
      "Crisp, light and mildly sweet Marie biscuits. The perfect companion for chai, coffee or a quick snack.",
    priceCents: 3500,
    categorySlug: "biscuits-snacks",
    emoji: "🍪",
    gradient: "from-yellow-100 to-amber-300",
    unit: "250 g pack",
    origin: "India",
    stock: 210,
    rating: 4.6,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["biscuit", "tea-time", "light"],
  },
  {
    name: "Britannia Cake Rusk",
    slug: "britannia-cake-rusk",
    description: "Crunchy sweet rusk for chai-time.",
    longDescription:
      "Golden cake rusks with a satisfying crunch. Dip in hot tea for the classic evening snack experience.",
    priceCents: 5500,
    categorySlug: "biscuits-snacks",
    emoji: "🥖",
    gradient: "from-orange-200 to-amber-400",
    unit: "200 g pack",
    origin: "India",
    stock: 170,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["rusk", "chai-time", "bakery"],
  },
  {
    name: "Apples Shimla",
    slug: "shimla-apples",
    description: "Crisp red apples from Himachal orchards.",
    longDescription:
      "Sweet, crunchy Shimla apples. Great for breakfast, kids' tiffin and healthy snacking throughout the day.",
    priceCents: 18900,
    categorySlug: "fresh-produce",
    emoji: "🍎",
    gradient: "from-red-200 to-rose-400",
    unit: "1 kg",
    origin: "Himachal Pradesh",
    stock: 70,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["fruit", "healthy", "tiffin"],
  },
  {
    name: "Carrots",
    slug: "carrots",
    description: "Fresh red carrots for salad, sabzi and halwa.",
    longDescription:
      "Crunchy red carrots, washed and sorted. Use for gajar halwa, salad, soups, mixed veg and lunch boxes.",
    priceCents: 5900,
    categorySlug: "fresh-produce",
    emoji: "🥕",
    gradient: "from-orange-200 to-red-300",
    unit: "1 kg",
    origin: "Nashik",
    stock: 120,
    rating: 4.4,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["vegetable", "salad", "halwa"],
  },
  {
    name: "Capsicum Green",
    slug: "green-capsicum",
    description: "Fresh shimla mirch for pizza, sabzi and noodles.",
    longDescription:
      "Firm green capsicum with crisp bite. Great for paneer, noodles, pizza toppings and stuffed capsicum.",
    priceCents: 6900,
    categorySlug: "fresh-produce",
    emoji: "🫑",
    gradient: "from-green-200 to-lime-400",
    unit: "500 g",
    origin: "Local farm",
    stock: 95,
    rating: 4.4,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["vegetable", "fresh", "noodles"],
  },
  {
    name: "Amul Paneer Fresh",
    slug: "amul-paneer-fresh",
    description: "Soft paneer cubes for curries and snacks.",
    longDescription:
      "Fresh, soft paneer from Amul. Perfect for paneer butter masala, palak paneer, tikka and tiffin rolls.",
    priceCents: 9900,
    categorySlug: "dairy-eggs",
    emoji: "🧀",
    gradient: "from-white to-yellow-200",
    unit: "200 g pack",
    origin: "Amul",
    stock: 75,
    rating: 4.7,
    reviewCount: 1,
    featured: true,
    organic: false,
    tags: ["paneer", "protein", "amul"],
  },
  {
    name: "Mother Dairy Lassi",
    slug: "mother-dairy-lassi",
    description: "Sweet Punjabi lassi, chilled and refreshing.",
    longDescription:
      "Thick, sweet lassi made from cultured milk. A refreshing drink after spicy meals or during hot afternoons.",
    priceCents: 3000,
    categorySlug: "dairy-eggs",
    emoji: "🥛",
    gradient: "from-blue-100 to-white",
    unit: "200 ml pack",
    origin: "Mother Dairy",
    stock: 110,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["lassi", "drink", "dairy"],
  },
  {
    name: "Britannia Cheese Cubes",
    slug: "britannia-cheese-cubes",
    description: "Creamy cheese cubes for snacks and lunch boxes.",
    longDescription:
      "Individually wrapped creamy cheese cubes. Great for kids, party platters and quick protein snacks.",
    priceCents: 12900,
    categorySlug: "dairy-eggs",
    emoji: "🧀",
    gradient: "from-yellow-300 to-orange-400",
    unit: "200 g pack",
    origin: "Britannia",
    stock: 65,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["cheese", "snacks", "kids"],
  },
  {
    name: "Milky Mist Curd Bucket",
    slug: "milky-mist-curd-bucket",
    description: "Family pack thick curd for raita and chaas.",
    longDescription:
      "Creamy set curd in a family bucket. Ideal for raita, chaas, kadhi and curd rice.",
    priceCents: 8900,
    categorySlug: "dairy-eggs",
    emoji: "🥛",
    gradient: "from-white to-cyan-100",
    unit: "1 kg bucket",
    origin: "India",
    stock: 80,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["curd", "family-pack", "dairy"],
  },
  {
    name: "Modern Sandwich Bread",
    slug: "modern-sandwich-bread",
    description: "Soft white sandwich bread for toast and tiffin.",
    longDescription:
      "Soft sliced white bread for quick sandwiches, toast, bread pakora and breakfast plates.",
    priceCents: 4500,
    categorySlug: "bakery-breakfast",
    emoji: "🍞",
    gradient: "from-amber-100 to-orange-200",
    unit: "400 g loaf",
    origin: "Modern",
    stock: 95,
    rating: 4.3,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["bread", "breakfast", "sandwich"],
  },
  {
    name: "Idli Rava",
    slug: "idli-rava",
    description: "Coarse rice rava for soft homemade idlis.",
    longDescription:
      "Premium idli rava that ferments well with urad dal. Makes soft, fluffy idlis and crisp dosas.",
    priceCents: 7900,
    categorySlug: "bakery-breakfast",
    emoji: "⚪",
    gradient: "from-white to-stone-200",
    unit: "1 kg pack",
    origin: "South India",
    stock: 110,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["idli", "breakfast", "south-indian"],
  },
  {
    name: "Dove Cream Beauty Bathing Bar",
    slug: "dove-beauty-bar",
    description: "Gentle moisturising soap with 1/4 cleansing cream.",
    longDescription:
      "A gentle beauty bar that cleanses without drying the skin. Perfect for daily bathing and sensitive skin.",
    priceCents: 6500,
    categorySlug: "personal-care",
    emoji: "🧼",
    gradient: "from-blue-100 to-white",
    unit: "100 g bar",
    origin: "HUL",
    stock: 130,
    rating: 4.7,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["soap", "skin-care", "moisturising"],
  },
  {
    name: "Head & Shoulders Anti-Dandruff Shampoo",
    slug: "head-shoulders-shampoo",
    description: "Anti-dandruff shampoo for clean scalp.",
    longDescription:
      "Classic anti-dandruff shampoo with refreshing clean feel. Helps reduce flakes and keeps hair manageable.",
    priceCents: 24900,
    categorySlug: "personal-care",
    emoji: "🧴",
    gradient: "from-blue-300 to-cyan-500",
    unit: "340 ml bottle",
    origin: "P&G",
    stock: 88,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["shampoo", "anti-dandruff", "hair-care"],
  },
  {
    name: "Dettol Handwash Original",
    slug: "dettol-handwash-original",
    description: "Germ protection liquid handwash refill.",
    longDescription:
      "Dettol original handwash refill for everyday germ protection. Keeps hands clean and fresh after cooking, cleaning and travel.",
    priceCents: 9900,
    categorySlug: "personal-care",
    emoji: "🧴",
    gradient: "from-green-300 to-emerald-500",
    unit: "750 ml refill",
    origin: "India",
    stock: 120,
    rating: 4.7,
    reviewCount: 1,
    featured: true,
    organic: false,
    tags: ["handwash", "germ-protection", "hygiene"],
  },
  {
    name: "Harpic Power Plus Toilet Cleaner",
    slug: "harpic-toilet-cleaner",
    description: "Thick liquid toilet cleaner for tough stains.",
    longDescription:
      "Powerful toilet cleaning liquid that removes limescale, stains and germs. Angled neck reaches under the rim easily.",
    priceCents: 19900,
    categorySlug: "household",
    emoji: "🚽",
    gradient: "from-blue-600 to-indigo-700",
    unit: "1 litre bottle",
    origin: "India",
    stock: 86,
    rating: 4.6,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["toilet-cleaner", "disinfectant", "household"],
  },
  {
    name: "Comfort Fabric Conditioner",
    slug: "comfort-fabric-conditioner",
    description: "Long-lasting fragrance and soft clothes.",
    longDescription:
      "Fabric conditioner that keeps clothes soft, fresh and easier to iron. A little capful makes laundry feel premium.",
    priceCents: 23500,
    categorySlug: "household",
    emoji: "🧺",
    gradient: "from-purple-300 to-pink-400",
    unit: "860 ml bottle",
    origin: "HUL",
    stock: 75,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["laundry", "fragrance", "softener"],
  },
  {
    name: "Scotch-Brite Scrub Pad",
    slug: "scotch-brite-scrub-pad",
    description: "Tough dish scrub pad for daily kitchen cleaning.",
    longDescription:
      "Durable scrub pad that removes stubborn grease from kadhais, tawas and pressure cookers without falling apart.",
    priceCents: 4500,
    categorySlug: "household",
    emoji: "🧽",
    gradient: "from-lime-300 to-green-500",
    unit: "pack of 3",
    origin: "3M",
    stock: 160,
    rating: 4.6,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["scrub", "kitchen", "cleaning"],
  },
  {
    name: "Aluminium Foil Roll",
    slug: "aluminium-foil-roll",
    description: "Food wrapping foil for rotis, baking and storage.",
    longDescription:
      "Strong food-grade aluminium foil roll. Keeps rotis warm, wraps tiffins and helps with baking and grilling.",
    priceCents: 12500,
    categorySlug: "household",
    emoji: "🥡",
    gradient: "from-slate-300 to-zinc-500",
    unit: "18 m roll",
    origin: "India",
    stock: 90,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["foil", "kitchen", "storage"],
  },
];

export const extraReviewSeed: ReviewSeed[] = [
  { productSlug: "24-mantra-organic-atta", author: "Namrata S.", rating: 5, title: "Organic and soft", body: "Rotis soft banti hain aur taste natural lagta hai. Premium quality.", verified: true },
  { productSlug: "daawat-rozana-basmati", author: "Ramesh G.", rating: 4, title: "Daily pulao rice", body: "Price ke hisaab se excellent. Pulao mein grains separate rehte hain.", verified: true },
  { productSlug: "brown-rice", author: "Nikita P.", rating: 4, title: "Healthy option", body: "Soak karke cook kiya, texture good and nutty taste.", verified: true },
  { productSlug: "besan-gram-flour", author: "Bhavana K.", rating: 5, title: "Pakoda crispy", body: "Besan fine hai, kadhi aur pakode dono perfect bane.", verified: true },
  { productSlug: "urad-dal-white", author: "Sridhar R.", rating: 5, title: "Idli batter perfect", body: "Batter nicely fermented. Idlis soft and fluffy.", verified: true },
  { productSlug: "green-moong-whole", author: "Alka T.", rating: 5, title: "Great sprouts", body: "Sprouting quality very good. Healthy breakfast ready.", verified: true },
  { productSlug: "black-chana", author: "Pallavi D.", rating: 4, title: "Clean kala chana", body: "No stones, cooked well after soaking overnight.", verified: true },
  { productSlug: "organic-groundnut-oil", author: "Ganesh M.", rating: 5, title: "Real shengdana tel", body: "Poha la khup chan flavour yeto. Ghee image sarkha nahi, bottle look premium aahe.", verified: true },
  { productSlug: "organic-groundnut-oil", author: "Sonali J.", rating: 5, title: "Cold pressed aroma", body: "Nutty aroma is strong and authentic. Worth the price.", verified: true },
  { productSlug: "parachute-coconut-oil", author: "Rupa N.", rating: 5, title: "Trusted brand", body: "Hair oiling ke liye best, pure coconut fragrance.", verified: true },
  { productSlug: "sesame-til-oil", author: "Madhav I.", rating: 4, title: "Pickle oil", body: "Achar mein use kiya, taste authentic aya.", verified: true },
  { productSlug: "coriander-powder", author: "Sonal B.", rating: 4, title: "Fresh dhania smell", body: "Everyday sabzi mein good flavour.", verified: true },
  { productSlug: "black-pepper-whole", author: "Chef Vinod", rating: 5, title: "Bold pepper", body: "Freshly crushed pepper has amazing aroma.", verified: true },
  { productSlug: "pav-bhaji-masala", author: "Mangesh S.", rating: 5, title: "Mumbai taste", body: "Ghar ka pav bhaji stall jaisa bana.", verified: true },
  { productSlug: "brown-sugar", author: "Aarohi K.", rating: 4, title: "Good for baking", body: "Cookies mein flavour rich aaya.", verified: true },
  { productSlug: "himalayan-pink-salt", author: "Jaya V.", rating: 5, title: "Nice mineral taste", body: "Salads and chaas ke liye perfect.", verified: true },
  { productSlug: "green-tea-bags", author: "Ritika P.", rating: 4, title: "Light and refreshing", body: "Evening green tea routine ke liye good.", verified: true },
  { productSlug: "bournvita-health-drink", author: "Seema R.", rating: 5, title: "Kids favourite", body: "Milk finish karne ka easiest way. Chocolate taste nice.", verified: true },
  { productSlug: "thums-up-soft-drink", author: "Akash M.", rating: 5, title: "Strong cola", body: "Biryani ke saath chilled Thums Up best.", verified: true },
  { productSlug: "maggi-2-minute-noodles", author: "Rohan K.", rating: 5, title: "Hostel memory", body: "Maggi kabhi disappoint nahi karti. Fresh stock.", verified: true },
  { productSlug: "maggi-2-minute-noodles", author: "Puja S.", rating: 5, title: "Kids love it", body: "Quick evening snack, always in our basket.", verified: true },
  { productSlug: "bingo-mad-angles-achari", author: "Tanya D.", rating: 4, title: "Chatpata", body: "Achari flavour strong and crunchy.", verified: true },
  { productSlug: "marie-gold-biscuits", author: "Aruna L.", rating: 5, title: "Light chai biscuit", body: "Not too sweet, tea ke saath perfect.", verified: true },
  { productSlug: "britannia-cake-rusk", author: "Dilip C.", rating: 4, title: "Crunchy rusk", body: "Tea dipping ke liye excellent.", verified: true },
  { productSlug: "shimla-apples", author: "Harsha B.", rating: 4, title: "Crisp apples", body: "Kids tiffin mein daily jaate hain.", verified: true },
  { productSlug: "carrots", author: "Anjali P.", rating: 4, title: "Fresh carrots", body: "Salad and gajar halwa dono ke liye nice.", verified: true },
  { productSlug: "green-capsicum", author: "Manasi N.", rating: 4, title: "Firm capsicum", body: "Noodles and pizza toppings good.", verified: true },
  { productSlug: "amul-paneer-fresh", author: "Nikhil S.", rating: 5, title: "Soft paneer", body: "Paneer butter masala restaurant style bana.", verified: true },
  { productSlug: "mother-dairy-lassi", author: "Rashmi K.", rating: 4, title: "Refreshing", body: "Lunch ke baad chilled lassi mast.", verified: true },
  { productSlug: "britannia-cheese-cubes", author: "Naina A.", rating: 4, title: "Kids snack", body: "Lunchbox favourite, individually packed.", verified: true },
  { productSlug: "milky-mist-curd-bucket", author: "Suresh T.", rating: 4, title: "Family pack dahi", body: "Raita and chaas ke liye enough quantity.", verified: true },
  { productSlug: "modern-sandwich-bread", author: "Payal W.", rating: 4, title: "Soft bread", body: "Sandwich and toast both good.", verified: true },
  { productSlug: "idli-rava", author: "Lakshmi V.", rating: 5, title: "Soft idlis", body: "Idli batter smooth and fermented well.", verified: true },
  { productSlug: "dove-beauty-bar", author: "Ira M.", rating: 5, title: "Gentle soap", body: "Skin dry nahi hoti. Premium feel.", verified: true },
  { productSlug: "head-shoulders-shampoo", author: "Vivek R.", rating: 4, title: "Works well", body: "Dandruff control noticeable after few washes.", verified: true },
  { productSlug: "dettol-handwash-original", author: "Mira S.", rating: 5, title: "Home essential", body: "Refill pack economical and trusted.", verified: true },
  { productSlug: "harpic-toilet-cleaner", author: "Pankaj D.", rating: 5, title: "Powerful cleaner", body: "Stains easily remove hotat. Good product.", verified: true },
  { productSlug: "comfort-fabric-conditioner", author: "Leena K.", rating: 4, title: "Nice fragrance", body: "Clothes soft and fresh smell for long.", verified: true },
  { productSlug: "scotch-brite-scrub-pad", author: "Omkar P.", rating: 5, title: "Durable scrub", body: "Kadhai and tawa cleaning easy. Doesn't tear quickly.", verified: true },
  { productSlug: "aluminium-foil-roll", author: "Chitra B.", rating: 4, title: "Good foil", body: "Tiffin rotis stay warm and fresh.", verified: true },
];
