import type { ProductSeed, ReviewSeed } from "./seed-data";

export const expandedProducts: ProductSeed[] = [
  // Staples & Grains (atta-rice-grains)
  {
    name: "Aashirvaad Select Sharbati Atta",
    slug: "aashirvaad-sharbati-atta",
    description: "Premium MP Sharbati wheat atta with natural sweetness.",
    longDescription: "Sharbati wheat from Sehore region of Madhya Pradesh, known for superior taste and golden colour. Makes soft rotis that stay fresh longer. Premium selection for special meals.",
    priceCents: 17500,
    categorySlug: "atta-rice-grains",
    emoji: "🌾",
    gradient: "from-amber-200 to-yellow-300",
    unit: "5 kg pack",
    origin: "Madhya Pradesh",
    stock: 125,
    rating: 4.9,
    reviewCount: 2,
    badge: "Premium",
    featured: true,
    organic: false,
    tags: ["sharbati", "premium", "soft-roti"],
  },
  {
    name: "India Gate Feast Rozana Basmati",
    slug: "india-gate-feast-basmati",
    description: "Affordable basmati for daily meals and pulao.",
    longDescription: "India Gate Feast Rozana - everyday basmati with good grain length and aroma. Economical choice for jeera rice, light pulao and office tiffin.",
    priceCents: 44900,
    categorySlug: "atta-rice-grains",
    emoji: "🍚",
    gradient: "from-stone-100 to-amber-200",
    unit: "5 kg pack",
    origin: "Punjab",
    stock: 140,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["basmati", "daily", "economical"],
  },
  {
    name: "Toor Dal Premium Unpolished",
    slug: "toor-dal-premium",
    description: "Farm-fresh toor dal with high protein content.",
    longDescription: "Premium unpolished toor dal sourced directly from Maharashtra farms. Cooks faster, tastes richer, retains more nutrients. Essential for daily dal-rice meals.",
    priceCents: 15900,
    compareAtCents: 18900,
    categorySlug: "atta-rice-grains",
    emoji: "🥣",
    gradient: "from-yellow-200 to-amber-300",
    unit: "1 kg pack",
    origin: "Maharashtra",
    stock: 180,
    rating: 4.8,
    reviewCount: 2,
    badge: "Farm Fresh",
    featured: true,
    organic: true,
    tags: ["unpolished", "protein", "farm-fresh"],
  },
  
  // Dal & Pulses (dal-pulses)
  {
    name: "Moong Dal Yellow Premium",
    slug: "moong-dal-yellow-premium",
    description: "Easy-to-digest moong dal for light meals.",
    longDescription: "Premium yellow moong dal, easy to digest and perfect for khichdi, dal fry, or sprouting. Rich in protein, suitable for all ages including children and elderly.",
    priceCents: 13900,
    categorySlug: "dal-pulses",
    emoji: "🟡",
    gradient: "from-yellow-200 to-lime-300",
    unit: "1 kg pack",
    origin: "Rajasthan",
    stock: 165,
    rating: 4.6,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["light", "digestible", "khichdi"],
  },
  {
    name: "Masoor Dal Whole Red",
    slug: "masoor-dal-whole-red",
    description: "Whole red masoor dal for traditional recipes.",
    longDescription: "Whole red masoor dal with skin intact, perfect for slow-cooked curries and traditional Bengali recipes. Rich in iron and fibre, excellent for vegetarian protein.",
    priceCents: 11900,
    categorySlug: "dal-pulses",
    emoji: "🔴",
    gradient: "from-red-300 to-orange-300",
    unit: "1 kg pack",
    origin: "Madhya Pradesh",
    stock: 145,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["whole", "iron-rich", "traditional"],
  },
  {
    name: "Kabuli Chana Large Premium",
    slug: "kabuli-chana-large",
    description: "Large kabuli chana for chole and salads.",
    longDescription: "Premium large kabuli chana (chickpeas), perfect for Punjabi chole, hummus, and healthy salads. Cooks evenly, retains shape, and has excellent taste.",
    priceCents: 14900,
    categorySlug: "dal-pulses",
    emoji: "⚪",
    gradient: "from-stone-100 to-amber-100",
    unit: "1 kg pack",
    origin: "Madhya Pradesh",
    stock: 135,
    rating: 4.7,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["large", "chole", "salad"],
  },

  // Oils & Ghee (oils-ghee)
  {
    name: "Patanjali Cow Ghee Premium",
    slug: "patanjali-cow-ghee",
    description: "Pure desi cow ghee with traditional bilona method.",
    longDescription: "Patanjali Cow Ghee made using traditional bilona method from pure cow milk. Rich in vitamins A, D, E, K. Perfect for tadka, parathas, and Ayurvedic wellness.",
    priceCents: 49900,
    compareAtCents: 54900,
    categorySlug: "oils-ghee",
    emoji: "🧈",
    gradient: "from-amber-200 to-yellow-300",
    unit: "1 L jar",
    origin: "Uttarakhand",
    stock: 95,
    rating: 4.6,
    reviewCount: 2,
    badge: "Bilona",
    featured: true,
    organic: false,
    tags: ["bilona", "desi", "ayurvedic"],
  },
  {
    name: "Fortune Rice Bran Health Oil",
    slug: "fortune-rice-bran-oil",
    description: "Heart-healthy rice bran oil with oryzanol.",
    longDescription: "Fortune Rice Bran Oil with natural oryzanol that helps maintain healthy cholesterol levels. High smoke point makes it ideal for deep frying and Indian cooking.",
    priceCents: 22900,
    categorySlug: "oils-ghee",
    emoji: "🍚",
    gradient: "from-yellow-100 to-amber-200",
    unit: "1 L bottle",
    origin: "India",
    stock: 155,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["heart-healthy", "oryzanol", "high-smoke-point"],
  },

  // Spices & Masalas (spices-masalas)
  {
    name: "MDH Kitchen King Masala",
    slug: "mdh-kitchen-king",
    description: "All-purpose masala for vegetables and curries.",
    longDescription: "MDH Kitchen King is a versatile spice blend perfect for all vegetables, paneer, and mixed curries. Balanced flavour profile makes cooking easy and delicious.",
    priceCents: 8500,
    categorySlug: "spices-masalas",
    emoji: "👑",
    gradient: "from-amber-300 to-orange-400",
    unit: "100 g pack",
    origin: "India",
    stock: 210,
    rating: 4.7,
    reviewCount: 2,
    badge: "Versatile",
    featured: true,
    organic: false,
    tags: ["all-purpose", "vegetables", "curries"],
  },
  {
    name: "Everest Chaat Masala",
    slug: "everest-chaat-masala",
    description: "Tangy chaat masala for street food taste.",
    longDescription: "Everest Chaat Masala brings authentic street food flavour to your home. Perfect for fruit chaat, raita, salads, and snacks. Tangy, spicy, and irresistible.",
    priceCents: 4500,
    categorySlug: "spices-masalas",
    emoji: "🍋",
    gradient: "from-lime-200 to-green-300",
    unit: "100 g pack",
    origin: "India",
    stock: 245,
    rating: 4.8,
    reviewCount: 2,
    badge: "Street Style",
    featured: true,
    organic: false,
    tags: ["chaat", "tangy", "street-food"],
  },
  {
    name: "Red Chilli Powder Guntur Special",
    slug: "red-chilli-guntur",
    description: "Fiery Guntur chilli powder with deep red colour.",
    longDescription: "Premium Guntur chilli powder known for intense heat and vibrant red colour. Essential for Andhra and South Indian cuisine. Use sparingly for authentic spiciness.",
    priceCents: 9500,
    categorySlug: "spices-masalas",
    emoji: "🌶️",
    gradient: "from-red-400 to-rose-500",
    unit: "200 g pack",
    origin: "Andhra Pradesh",
    stock: 175,
    rating: 4.6,
    reviewCount: 1,
    badge: "Fiery",
    featured: false,
    organic: false,
    tags: ["guntur", "spicy", "south-indian"],
  },
  {
    name: "Turmeric Powder Salem Premium",
    slug: "turmeric-salem-premium",
    description: "High curcumin Salem turmeric for health and colour.",
    longDescription: "Premium Salem turmeric with high curcumin content (5-6%). Vibrant golden colour, earthy aroma, and medicinal properties. Essential for daily cooking and wellness.",
    priceCents: 7500,
    categorySlug: "spices-masalas",
    emoji: "🟨",
    gradient: "from-yellow-300 to-amber-400",
    unit: "200 g pack",
    origin: "Tamil Nadu",
    stock: 195,
    rating: 4.8,
    reviewCount: 2,
    badge: "High Curcumin",
    featured: true,
    organic: false,
    tags: ["salem", "curcumin", "medicinal"],
  },

  // Tea, Coffee & Beverages (tea-coffee)
  {
    name: "Tata Tea Agni Strong",
    slug: "tata-tea-agni",
    description: "Strong kadak chai for tea lovers.",
    longDescription: "Tata Tea Agni delivers strong, kadak chai with rich colour and bold taste. Perfect for morning energy boost and evening refreshment. Loved by strong tea drinkers.",
    priceCents: 11500,
    categorySlug: "tea-coffee",
    emoji: "☕",
    gradient: "from-amber-700 to-stone-800",
    unit: "500 g pack",
    origin: "Assam",
    stock: 165,
    rating: 4.7,
    reviewCount: 2,
    badge: "Kadak",
    featured: true,
    organic: false,
    tags: ["strong", "kadak", "bold"],
  },
  {
    name: "Bru Gold Premium Instant Coffee",
    slug: "bru-gold-premium",
    description: "Premium instant coffee with rich aroma.",
    longDescription: "Bru Gold Premium is 100% pure instant coffee with rich aroma and smooth taste. Dissolves instantly in hot or cold milk. Perfect for busy mornings.",
    priceCents: 18900,
    compareAtCents: 21900,
    categorySlug: "tea-coffee",
    emoji: "☕",
    gradient: "from-stone-700 to-amber-800",
    unit: "200 g jar",
    origin: "India",
    stock: 125,
    rating: 4.6,
    reviewCount: 1,
    badge: "Premium",
    featured: true,
    organic: false,
    tags: ["instant", "aroma", "smooth"],
  },
  {
    name: "Pepsi Black Zero Sugar Can",
    slug: "pepsi-black-zero",
    description: "Zero sugar cola with bold taste.",
    longDescription: "Pepsi Black - zero sugar, zero calories, but full bold cola taste. Perfect when you want refreshing drink without sugar guilt. Serve chilled for best experience.",
    priceCents: 4000,
    categorySlug: "tea-coffee",
    emoji: "🥤",
    gradient: "from-stone-900 to-stone-700",
    unit: "300 ml can (6 pack)",
    origin: "India",
    stock: 220,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["zero-sugar", "cola", "chilled"],
  },
  {
    name: "Frooti Mango Drink",
    slug: "frooti-mango-drink",
    description: "Fresh mango taste in every sip.",
    longDescription: "Frooti - India's favourite mango drink with real Alphonso mango pulp. Refreshing, sweet, and perfect for summer. Kids and adults both love the authentic mango taste.",
    priceCents: 2000,
    categorySlug: "tea-coffee",
    emoji: "🥭",
    gradient: "from-yellow-300 to-orange-400",
    unit: "1.2 L tetra pack",
    origin: "India",
    stock: 185,
    rating: 4.7,
    reviewCount: 2,
    badge: "Summer Special",
    featured: true,
    organic: false,
    tags: ["mango", "alphonso", "refreshing"],
  },

  // Biscuits & Snacks (biscuits-snacks)
  {
    name: "Parle Hide & Seek Milano",
    slug: "parle-hide-seek-milano",
    description: "Premium chocolate chip cookies with rich taste.",
    longDescription: "Parle Hide & Seek Milano - premium cookies with generous chocolate chips in every bite. Crispy texture with rich chocolate flavour. Perfect with tea or coffee.",
    priceCents: 4500,
    categorySlug: "biscuits-snacks",
    emoji: "🍪",
    gradient: "from-amber-700 to-stone-800",
    unit: "120 g pack",
    origin: "India",
    stock: 195,
    rating: 4.8,
    reviewCount: 2,
    badge: "Premium",
    featured: true,
    organic: false,
    tags: ["chocolate-chip", "premium", "milano"],
  },
  {
    name: "Kurkure Masala Munch Crisps",
    slug: "kurkure-masala-crisps",
    description: "Crunchy masala-flavoured corn snacks.",
    longDescription: "Kurkure Masala Munch - crunchy corn snacks with spicy masala coating. Irresistible taste that keeps you coming back for more. Perfect evening snack with chai.",
    priceCents: 2000,
    categorySlug: "biscuits-snacks",
    emoji: "🌽",
    gradient: "from-orange-300 to-red-400",
    unit: "90 g pack",
    origin: "India",
    stock: 265,
    rating: 4.6,
    reviewCount: 2,
    featured: false,
    organic: false,
    tags: ["corn", "masala", "crunchy"],
  },
  {
    name: "Uncle Chipps Spicy Treat",
    slug: "uncle-chipps-spicy",
    description: "Spicy potato chips with bold flavour.",
    longDescription: "Uncle Chipps Spicy Treat - crispy potato chips with bold spicy seasoning. Perfect crunch in every bite. Great for parties, movie nights, and snacking.",
    priceCents: 2000,
    categorySlug: "biscuits-snacks",
    emoji: "🥔",
    gradient: "from-red-400 to-orange-500",
    unit: "52 g pack",
    origin: "India",
    stock: 285,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["potato", "spicy", "crispy"],
  },
  {
    name: "Britannia NutriChoice Digestive Biscuits",
    slug: "britannia-nutrichoice-digestive",
    description: "Whole wheat digestive biscuits for healthy snacking.",
    longDescription: "Britannia NutriChoice Digestive - made with whole wheat and high fibre. Perfect for health-conscious snacking. Good source of dietary fibre and essential nutrients.",
    priceCents: 4500,
    categorySlug: "biscuits-snacks",
    emoji: "🍪",
    gradient: "from-amber-200 to-yellow-300",
    unit: "300 g pack",
    origin: "India",
    stock: 245,
    rating: 4.6,
    reviewCount: 2,
    badge: "High Fibre",
    featured: true,
    organic: false,
    tags: ["digestive", "whole-wheat", "healthy"],
  },

  // Fresh Produce (fresh-produce)
  {
    name: "Fresh Tomatoes Local",
    slug: "tomatoes-local",
    description: "Farm-fresh red tomatoes for daily cooking.",
    longDescription: "Fresh local tomatoes, hand-picked at peak ripeness. Perfect for curries, salads, soups, and chutneys. Rich in lycopene and vitamin C.",
    priceCents: 4000,
    categorySlug: "fresh-produce",
    emoji: "🍅",
    gradient: "from-red-400 to-rose-500",
    unit: "1 kg",
    origin: "Local farms",
    stock: 150,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["fresh", "daily", "lycopene"],
  },
  {
    name: "Fresh Onions Nashik",
    slug: "onions-nashik",
    description: "Premium Nashik onions for Indian cooking.",
    longDescription: "Fresh Nashik onions - the gold standard for Indian cooking. Firm, pungent, and perfect for curries, salads, and tadka. Essential kitchen staple.",
    priceCents: 3500,
    categorySlug: "fresh-produce",
    emoji: "🧅",
    gradient: "from-amber-200 to-stone-300",
    unit: "1 kg",
    origin: "Nashik, Maharashtra",
    stock: 200,
    rating: 4.6,
    reviewCount: 2,
    featured: false,
    organic: false,
    tags: ["nashik", "essential", "pungent"],
  },
  {
    name: "Fresh Potatoes Agra",
    slug: "potatoes-agra",
    description: "Firm Agra potatoes for versatile cooking.",
    longDescription: "Fresh Agra potatoes - firm, versatile, and perfect for curries, fries, chips, and aloo parathas. Clean, sorted, and ready to cook.",
    priceCents: 3000,
    categorySlug: "fresh-produce",
    emoji: "🥔",
    gradient: "from-amber-100 to-stone-200",
    unit: "1 kg",
    origin: "Agra, UP",
    stock: 180,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["agra", "versatile", "firm"],
  },
  {
    name: "Fresh Coriander Leaves",
    slug: "coriander-fresh",
    description: "Aromatic fresh coriander for garnish and chutney.",
    longDescription: "Fresh coriander leaves (dhania) - aromatic herb essential for Indian cooking. Perfect for garnish, chutneys, and raitas. Adds fresh flavour to every dish.",
    priceCents: 1000,
    categorySlug: "fresh-produce",
    emoji: "🌿",
    gradient: "from-green-400 to-emerald-500",
    unit: "100 g bunch",
    origin: "Local farms",
    stock: 120,
    rating: 4.7,
    reviewCount: 2,
    featured: false,
    organic: false,
    tags: ["herb", "garnish", "aromatic"],
  },
  {
    name: "Fresh Green Chillies",
    slug: "green-chillies-fresh",
    description: "Spicy green chillies for authentic Indian heat.",
    longDescription: "Fresh green chillies - essential for authentic Indian cooking. Adds heat and flavour to curries, chutneys, and pickles. Use as per spice tolerance.",
    priceCents: 800,
    categorySlug: "fresh-produce",
    emoji: "🌶️",
    gradient: "from-green-500 to-emerald-600",
    unit: "100 g",
    origin: "Local farms",
    stock: 95,
    rating: 4.6,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["spicy", "essential", "authentic"],
  },

  // Dairy & Eggs (dairy-eggs)
  {
    name: "Amul Taaza Homogenised Milk",
    slug: "amul-taaza-homogenised",
    description: "Homogenised toned milk with consistent cream.",
    longDescription: "Amul Taaza Homogenised - toned milk with consistent cream distribution throughout. Pasteurised for safety, perfect for tea, coffee, and daily consumption.",
    priceCents: 3000,
    categorySlug: "dairy-eggs",
    emoji: "🥛",
    gradient: "from-blue-100 to-sky-200",
    unit: "1 L pack",
    origin: "Gujarat",
    stock: 220,
    rating: 4.7,
    reviewCount: 2,
    featured: false,
    organic: false,
    tags: ["homogenised", "toned", "daily"],
  },
  {
    name: "Mother Dairy Ice Cream Vanilla",
    slug: "mother-dairy-ice-cream-vanilla",
    description: "Creamy vanilla ice cream tub for family enjoyment.",
    longDescription: "Mother Dairy Vanilla Ice Cream - rich and creamy vanilla flavour made with fresh milk. Perfect for desserts, sundaes, and family gatherings. Smooth texture with authentic vanilla taste.",
    priceCents: 15000,
    categorySlug: "dairy-eggs",
    emoji: "🍦",
    gradient: "from-blue-100 to-sky-200",
    unit: "1 L tub",
    origin: "India",
    stock: 120,
    rating: 4.7,
    reviewCount: 2,
    badge: "Family Pack",
    featured: true,
    organic: false,
    tags: ["ice-cream", "vanilla", "dessert"],
  },
  {
    name: "Farm Fresh Eggs Brown",
    slug: "eggs-brown-farm",
    description: "Farm-fresh brown eggs from free-range hens.",
    longDescription: "Farm-fresh brown eggs from free-range hens. Rich in protein, vitamins, and omega-3. Perfect for breakfast, baking, and daily nutrition.",
    priceCents: 7500,
    categorySlug: "dairy-eggs",
    emoji: "🥚",
    gradient: "from-amber-100 to-orange-200",
    unit: "12 eggs (1 dozen)",
    origin: "Local farms",
    stock: 165,
    rating: 4.8,
    reviewCount: 2,
    badge: "Free Range",
    featured: true,
    organic: false,
    tags: ["brown", "free-range", "protein"],
  },

  // Bakery & Breakfast (bakery-breakfast)
  {
    name: "Modern Sandwich Bread White",
    slug: "modern-bread-white",
    description: "Soft white bread for sandwiches and toast.",
    longDescription: "Modern Sandwich Bread - soft, fresh white bread perfect for sandwiches, toast, and bread pakoras. Made with quality wheat flour. Family favourite.",
    priceCents: 4500,
    categorySlug: "bakery-breakfast",
    emoji: "🍞",
    gradient: "from-amber-100 to-yellow-200",
    unit: "400 g loaf",
    origin: "India",
    stock: 175,
    rating: 4.5,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["white", "soft", "sandwich"],
  },
  {
    name: "Quaker Oats Rolled",
    slug: "quaker-oats-rolled",
    description: "Heart-healthy rolled oats for breakfast.",
    longDescription: "Quaker Oats - 100% whole grain rolled oats. Rich in soluble fibre that helps maintain healthy cholesterol. Quick-cooking, perfect for porridge and smoothies.",
    priceCents: 12900,
    categorySlug: "bakery-breakfast",
    emoji: "🥣",
    gradient: "from-amber-200 to-yellow-300",
    unit: "1 kg pack",
    origin: "India",
    stock: 135,
    rating: 4.7,
    reviewCount: 2,
    badge: "Heart Healthy",
    featured: true,
    organic: false,
    tags: ["rolled", "fibre", "cholesterol"],
  },
  {
    name: "Kissan Mixed Fruit Jam",
    slug: "kissan-jam-mixed",
    description: "Real fruit jam for bread and parathas.",
    longDescription: "Kissan Mixed Fruit Jam - made with real fruit pulp and natural flavours. Perfect spread for bread, parathas, and pancakes. Kids love the fruity taste.",
    priceCents: 8500,
    categorySlug: "bakery-breakfast",
    emoji: "🍓",
    gradient: "from-rose-300 to-pink-400",
    unit: "500 g jar",
    origin: "India",
    stock: 155,
    rating: 4.6,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["fruit", "spread", "kids"],
  },

  // Personal Care (personal-care)

  {
    name: "Santoor Body Wash Sandalwood",
    slug: "santoor-body-wash-sandalwood",
    description: "Refreshing body wash with sandalwood and turmeric.",
    longDescription: "Santoor Body Wash - enriched with sandalwood and turmeric extracts. Cleanses gently while keeping skin soft and radiant. Pleasant fragrance that lasts all day.",
    priceCents: 18500,
    categorySlug: "personal-care",
    emoji: "🧴",
    gradient: "from-amber-200 to-orange-300",
    unit: "400 ml bottle",
    origin: "India",
    stock: 135,
    rating: 4.6,
    reviewCount: 2,
    badge: "Skin Care",
    featured: true,
    organic: false,
    tags: ["body-wash", "sandalwood", "turmeric"],
  },
  {
    name: "Ponds Dreamflower Talcum Powder",
    slug: "ponds-dreamflower",
    description: "Fresh talcum powder with floral fragrance.",
    longDescription: "Ponds Dreamflower - classic talcum powder with refreshing floral fragrance. Keeps skin cool, dry, and fresh all day. Trusted for generations.",
    priceCents: 7500,
    categorySlug: "personal-care",
    emoji: "🌸",
    gradient: "from-pink-200 to-rose-300",
    unit: "200 g bottle",
    origin: "India",
    stock: 185,
    rating: 4.6,
    reviewCount: 1,
    badge: "Classic",
    featured: true,
    organic: false,
    tags: ["floral", "fresh", "classic"],
  },

  // Household & Cleaning (household)

  {
    name: "Good Knight Gold Flash Mosquito Repellent",
    slug: "good-knight-gold",
    description: "Advanced mosquito repellent for peaceful nights.",
    longDescription: "Good Knight Gold Flash - advanced liquid vaporiser that provides all-night protection from mosquitoes. Pleasant fragrance, effective formula. Sleep peacefully.",
    priceCents: 8500,
    categorySlug: "household",
    emoji: "🦟",
    gradient: "from-amber-300 to-yellow-400",
    unit: "Machine + 2 refills",
    origin: "India",
    stock: 165,
    rating: 4.6,
    reviewCount: 1,
    badge: "All Night",
    featured: true,
    organic: false,
    tags: ["mosquito", "night", "protection"],
  },
  {
    name: "Agarbatti Fragrance Sticks",
    slug: "agarbatti-fragrance",
    description: "Premium incense sticks for spiritual ambience.",
    longDescription: "Premium agarbatti with long-lasting fragrance. Creates peaceful, spiritual ambience for prayer and meditation. Natural ingredients, no harmful chemicals.",
    priceCents: 4500,
    categorySlug: "household",
    emoji: "🕯️",
    gradient: "from-amber-200 to-orange-300",
    unit: "Pack of 100 sticks",
    origin: "India",
    stock: 225,
    rating: 4.8,
    reviewCount: 2,
    badge: "Premium",
    featured: true,
    organic: false,
    tags: ["incense", "spiritual", "natural"],
  },
];

export const expandedReviews: ReviewSeed[] = [
  { productSlug: "aashirvaad-sharbati-atta", author: "Priya Sharma", rating: 5, title: "Best atta for rotis", body: "Sharbati atta makes the softest rotis. Natural sweetness is noticeable. Worth the premium price.", verified: true },
  { productSlug: "aashirvaad-sharbati-atta", author: "Rahul Mehta", rating: 5, title: "Premium quality", body: "You can taste the difference. Rotis stay soft even after hours. Family loves it.", verified: true },
  { productSlug: "toor-dal-premium", author: "Sunita Patil", rating: 5, title: "Farm fresh taste", body: "Unpolished dal has authentic taste. Cooks faster than regular dal. Highly recommended.", verified: true },
  { productSlug: "toor-dal-premium", author: "Amit Deshmukh", rating: 4, title: "Good quality", body: "Clean dal with no stones. Taste is good, protein content is high. Will buy again.", verified: true },
  { productSlug: "patanjali-cow-ghee", author: "Geeta Iyer", rating: 5, title: "Authentic bilona ghee", body: "Smells and tastes like traditional ghee. Granular texture is perfect. Using for cooking and Ayurveda.", verified: true },
  { productSlug: "patanjali-cow-ghee", author: "Vikram Singh", rating: 4, title: "Good value", body: "Quality is good for the price. Aroma is pleasant. Use daily for tadka and parathas.", verified: true },
  { productSlug: "mdh-kitchen-king", author: "Neha Kapoor", rating: 5, title: "Versatile masala", body: "Use it for all vegetables. Balanced flavour, not too spicy. Makes cooking easy.", verified: true },
  { productSlug: "mdh-kitchen-king", author: "Sanjay Gupta", rating: 4, title: "Good all-rounder", body: "Works well for paneer and mixed veg. Taste is consistent. Good value for money.", verified: true },
  { productSlug: "everest-chaat-masala", author: "Anjali Reddy", rating: 5, title: "Perfect for chaat", body: "Authentic street food taste at home. Tangy and spicy balance is perfect. Use it on fruits too.", verified: true },
  { productSlug: "everest-chaat-masala", author: "Karan Malhotra", rating: 5, title: "Addictive taste", body: "Cannot stop using it. Sprinkle on everything - salads, raita, snacks. Amazing flavour.", verified: true },
  { productSlug: "tata-tea-agni", author: "Ramesh Kumar", rating: 5, title: "Strong kadak chai", body: "Perfect for strong tea lovers. Rich colour and bold taste. Morning essential.", verified: true },
  { productSlug: "tata-tea-agni", author: "Lakshmi Nair", rating: 4, title: "Good strong tea", body: "Strong flavour as promised. Good for cutting chai. Economical price.", verified: true },
  { productSlug: "bru-gold-premium", author: "Deepak Joshi", rating: 5, title: "Rich aroma", body: "Instant coffee with café-like aroma. Smooth taste, not bitter. Dissolves well in milk.", verified: true },
  { productSlug: "frooti-mango-drink", author: "Sneha Patel", rating: 5, title: "Kids love it", body: "Authentic mango taste. Kids ask for it every summer. Refreshing and tasty.", verified: true },
  { productSlug: "frooti-mango-drink", author: "Arjun Verma", rating: 4, title: "Summer favourite", body: "Good mango flavour. Sweet and refreshing. Perfect for hot days.", verified: true },
  { productSlug: "parle-hide-seek-milano", author: "Kavita Desai", rating: 5, title: "Premium cookies", body: "Generous chocolate chips in every bite. Crispy texture. Perfect with evening tea.", verified: true },
  { productSlug: "parle-hide-seek-milano", author: "Rohan Sharma", rating: 5, title: "Best chocolate cookies", body: "Rich chocolate taste. Quality is premium. Will definitely buy again.", verified: true },
  { productSlug: "bingo-mad-angles-achari", author: "Pooja Jain", rating: 5, title: "Unique taste", body: "Triangle shape is fun. Achari flavour is tangy and spicy. Addictive snack.", verified: true },
  { productSlug: "bingo-mad-angles-achari", author: "Vikas Yadav", rating: 4, title: "Good evening snack", body: "Crunchy and tasty. Achari masala is different from regular chips. Enjoy with chai.", verified: true },
  { productSlug: "haldiram-aloo-bhujia", author: "Meera Agarwal", rating: 5, title: "Authentic Rajasthani", body: "Tastes just like Bikaner bhujia. Thin, crispy, perfect spice. Tea-time essential.", verified: true },
  { productSlug: "haldiram-aloo-bhujia", author: "Suresh Menon", rating: 5, title: "Classic namkeen", body: "Family favourite. Quality is consistent. Perfect for guests and parties.", verified: true },
  { productSlug: "haldiram-aloo-bhujia", author: "Anita Bhatt", rating: 5, title: "Irresistible", body: "Cannot stop eating once started. Authentic taste. Always keep stock at home.", verified: true },
  { productSlug: "lays-classic-salted", author: "Nikhil Chopra", rating: 5, title: "Perfect crunch", body: "Classic taste never disappoints. Crispy, light, perfectly salted. World's best snack.", verified: true },
  { productSlug: "lays-classic-salted", author: "Ritu Saxena", rating: 4, title: "Good quality", body: "Fresh chips with good crunch. Salt level is perfect. Kids love it.", verified: true },
  { productSlug: "lays-classic-salted", author: "Arun Prakash", rating: 5, title: "Party favourite", body: "Always buy for parties. Everyone loves it. Quality is consistent.", verified: true },
  { productSlug: "onions-nashik", author: "Sunita Kulkarni", rating: 5, title: "Premium onions", body: "Nashik onions are best. Firm, pungent, perfect for cooking. No spoilage.", verified: true },
  { productSlug: "onions-nashik", author: "Rajesh Patil", rating: 4, title: "Good quality", body: "Clean and sorted onions. Size is uniform. Good for daily cooking.", verified: true },
  { productSlug: "coriander-fresh", author: "Meenakshi Rao", rating: 5, title: "Aromatic herbs", body: "Fresh coriander with strong aroma. Clean, no yellow leaves. Perfect for garnish.", verified: true },
  { productSlug: "coriander-fresh", author: "Vijay Hegde", rating: 4, title: "Good freshness", body: "Leaves are green and fresh. Aroma is good. Use for chutney and garnish.", verified: true },
  { productSlug: "eggs-brown-farm", author: "Pallavi Deshpande", rating: 5, title: "Farm fresh eggs", body: "Brown eggs have rich yolk colour. Taste is better than white eggs. Free range is good.", verified: true },
  { productSlug: "eggs-brown-farm", author: "Ashwin Iyer", rating: 5, title: "Quality eggs", body: "Yolk is deep orange. No bad eggs in the pack. Freshness is excellent.", verified: true },
  { productSlug: "quaker-oats-rolled", author: "Divya Nair", rating: 5, title: "Healthy breakfast", body: "Rolled oats cook quickly. Good fibre content. Perfect for weight management.", verified: true },
  { productSlug: "quaker-oats-rolled", author: "Manish Tiwari", rating: 4, title: "Good quality oats", body: "Texture is good. Cooks in 2-3 minutes. Healthy breakfast option.", verified: true },
  { productSlug: "lifebuoy-soap", author: "Suman Devi", rating: 5, title: "Family protection", body: "Use for entire family. Germ protection is effective. Pleasant fragrance.", verified: true },
  { productSlug: "lifebuoy-soap", author: "Prakash Kumar", rating: 4, title: "Good soap", body: "Cleans well, fragrance is good. Affordable price. Daily use soap.", verified: true },
  { productSlug: "ponds-dreamflower", author: "Kavita Sharma", rating: 5, title: "Classic fragrance", body: "Childhood memories. Floral scent is refreshing. Keeps skin fresh all day.", verified: true },
  { productSlug: "vim-dishwash", author: "Anjali Menon", rating: 5, title: "Cuts grease easily", body: "Lemon fragrance is pleasant. Cleans oily utensils well. Economical to use.", verified: true },
  { productSlug: "vim-dishwash", author: "Suresh Babu", rating: 4, title: "Good cleaner", body: "Effective on tough stains. Lemon smell is nice. Good value for money.", verified: true },
  { productSlug: "good-knight-gold", author: "Rekha Verma", rating: 5, title: "Peaceful sleep", body: "No mosquito bites all night. Fragrance is mild and pleasant. Effective formula.", verified: true },
  { productSlug: "agarbatti-fragrance", author: "Lakshmi Iyer", rating: 5, title: "Divine fragrance", body: "Long-lasting smell. Creates peaceful atmosphere for prayer. Natural ingredients.", verified: true },
  { productSlug: "agarbatti-fragrance", author: "Ramesh Bhat", rating: 5, title: "Premium quality", body: "Fragrance is authentic. Burns evenly. Good for meditation and prayer.", verified: true },
];
