import type { ProductSeed, ReviewSeed } from "./seed-data";

export const originalExpansionProducts: ProductSeed[] = [
  {
    name: "Cadbury Oreo Original Vanilla Biscuits",
    slug: "cadbury-oreo-original",
    description: "Chocolate sandwich biscuits with smooth vanilla crème.",
    longDescription: "Cadbury Oreo Original combines crunchy cocoa biscuits with a smooth vanilla crème centre. Twist, lick, dunk, or enjoy straight from the pack — a favourite for snacks and desserts.",
    priceCents: 3000,
    categorySlug: "biscuits-snacks",
    emoji: "🍪",
    gradient: "from-blue-700 to-sky-400",
    unit: "120 g pack",
    origin: "India",
    stock: 240,
    rating: 4.8,
    reviewCount: 2,
    badge: "Bestseller",
    featured: true,
    organic: false,
    tags: ["oreo", "vanilla", "sandwich-biscuit"],
  },
  {
    name: "Nestle KitKat Chunky Wafer Bar",
    slug: "kitkat-chunky",
    description: "Crispy chunky wafer coated in smooth milk chocolate.",
    longDescription: "Nestle KitKat Chunky delivers a satisfying crunchy wafer covered in rich milk chocolate. A bigger, crunchier break for work, travel, or an afternoon treat.",
    priceCents: 6000,
    categorySlug: "biscuits-snacks",
    emoji: "🍫",
    gradient: "from-red-600 to-rose-400",
    unit: "40 g bar",
    origin: "India",
    stock: 190,
    rating: 4.7,
    reviewCount: 1,
    badge: "New",
    featured: true,
    organic: false,
    tags: ["kitkat", "wafer", "chocolate"],
  },
  {
    name: "Snickers Peanut Caramel Chocolate Bar",
    slug: "snickers-chocolate",
    description: "Peanuts, caramel and nougat wrapped in milk chocolate.",
    longDescription: "Snickers combines roasted peanuts, creamy caramel and soft nougat under a milk chocolate coating. A filling chocolate bar for hunger between meals.",
    priceCents: 12500,
    compareAtCents: 14000,
    categorySlug: "biscuits-snacks",
    emoji: "🥜",
    gradient: "from-blue-900 to-amber-500",
    unit: "80 g bar",
    origin: "India",
    stock: 155,
    rating: 4.7,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["peanut", "caramel", "chocolate"],
  },
  {
    name: "Sprite Lemon & Lime Soft Drink",
    slug: "sprite-lemon",
    description: "Crisp caffeine-free lemon-lime carbonated drink.",
    longDescription: "Sprite offers a clean, crisp lemon and lime taste with lively carbonation. Serve ice-cold with meals, snacks, or at parties.",
    priceCents: 7000,
    categorySlug: "tea-coffee",
    emoji: "🥤",
    gradient: "from-emerald-500 to-lime-300",
    unit: "1.25 L bottle",
    origin: "India",
    stock: 180,
    rating: 4.6,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["sprite", "lemon-lime", "cold-drink"],
  },
  {
    name: "Red Bull Energy Drink",
    slug: "red-bull-energy",
    description: "Energy drink with caffeine, taurine and B vitamins.",
    longDescription: "Red Bull Energy Drink is formulated with caffeine, taurine and B-group vitamins to support alertness and energy. Best served chilled and consumed responsibly.",
    priceCents: 12500,
    categorySlug: "tea-coffee",
    emoji: "⚡",
    gradient: "from-blue-700 to-slate-200",
    unit: "250 ml can",
    origin: "India",
    stock: 145,
    rating: 4.7,
    reviewCount: 1,
    badge: "Energy",
    featured: true,
    organic: false,
    tags: ["energy-drink", "caffeine", "taurine"],
  },
  {
    name: "Ariel Matic Top Load Detergent Powder",
    slug: "ariel-matic-top-load",
    description: "Machine detergent formulated for top-load washing machines.",
    longDescription: "Ariel Matic Top Load removes tough stains in one wash and dissolves quickly without leaving powder residue. Designed especially for fully automatic top-load machines.",
    priceCents: 45100,
    compareAtCents: 59500,
    categorySlug: "household",
    emoji: "🧺",
    gradient: "from-emerald-500 to-blue-500",
    unit: "2 kg pack",
    origin: "India",
    stock: 110,
    rating: 4.8,
    reviewCount: 2,
    badge: "Super Saver",
    featured: true,
    organic: false,
    tags: ["ariel", "top-load", "detergent"],
  },
  {
    name: "Tide Plus Lemon & Mint Detergent Powder",
    slug: "tide-lemon-mint",
    description: "Deep-cleaning detergent with fresh lemon and mint fragrance.",
    longDescription: "Tide Plus removes deep-seated stains while leaving clothes with a fresh lemon and mint fragrance. Suitable for both bucket wash and washing machines.",
    priceCents: 13000,
    categorySlug: "household",
    emoji: "🫧",
    gradient: "from-orange-500 to-yellow-300",
    unit: "1 kg pack",
    origin: "India",
    stock: 165,
    rating: 4.7,
    reviewCount: 1,
    featured: false,
    organic: false,
    tags: ["tide", "lemon-mint", "laundry"],
  },
  {
    name: "Pears Pure & Gentle Bathing Soap",
    slug: "pears-pure-gentle",
    description: "Transparent glycerine soap for gentle daily cleansing.",
    longDescription: "Pears Pure & Gentle is a transparent bathing bar with natural glycerine. Its mild formula cleanses while helping preserve skin moisture and softness.",
    priceCents: 14700,
    compareAtCents: 16400,
    categorySlug: "personal-care",
    emoji: "🧼",
    gradient: "from-amber-300 to-orange-400",
    unit: "4 × 75 g pack",
    origin: "India",
    stock: 135,
    rating: 4.8,
    reviewCount: 2,
    badge: "Gentle Care",
    featured: true,
    organic: false,
    tags: ["pears", "glycerine", "gentle"],
  },
];

export const originalExpansionReviews: ReviewSeed[] = [
  { productSlug: "cadbury-oreo-original", author: "Riya K.", rating: 5, title: "Classic Oreo", body: "Fresh crunchy biscuits and creamy filling. Perfect for milkshakes too.", verified: true },
  { productSlug: "cadbury-oreo-original", author: "Aman P.", rating: 5, title: "Kids favourite", body: "Pack arrived fresh and the children finished it quickly.", verified: true },
  { productSlug: "kitkat-chunky", author: "Mehul S.", rating: 5, title: "Great crunch", body: "Thick chocolate and crunchy wafer make a satisfying snack.", verified: true },
  { productSlug: "snickers-chocolate", author: "Neha D.", rating: 5, title: "Filling snack", body: "Good mix of peanuts, caramel and chocolate. Great for travel.", verified: true },
  { productSlug: "sprite-lemon", author: "Karan M.", rating: 5, title: "Crisp and refreshing", body: "Delivered chilled and tasted great with dinner.", verified: true },
  { productSlug: "red-bull-energy", author: "Arjun V.", rating: 5, title: "Original can", body: "Authentic sealed can with good expiry and quick delivery.", verified: true },
  { productSlug: "ariel-matic-top-load", author: "Sunita R.", rating: 5, title: "Excellent for machine wash", body: "Removes collar stains and leaves no powder residue in the top-load machine.", verified: true },
  { productSlug: "ariel-matic-top-load", author: "Nilesh T.", rating: 5, title: "Value pack", body: "Good discount and strong stain removal. Clothes smell fresh.", verified: true },
  { productSlug: "tide-lemon-mint", author: "Kavita B.", rating: 5, title: "Fresh laundry", body: "Cleans daily clothes well and has a pleasant lemon fragrance.", verified: true },
  { productSlug: "pears-pure-gentle", author: "Pooja N.", rating: 5, title: "Gentle on skin", body: "Does not dry out my skin and the original transparent bar looks premium.", verified: true },
  { productSlug: "pears-pure-gentle", author: "Rekha A.", rating: 5, title: "Trusted soap", body: "Original pack, nice fragrance and good value for four bars.", verified: true },
];
